/*

--COMANDOS PARA EXECUÇÃO

- LISTA DE PARENTESCO

Companheiro(a)
Esposo(a)
Pai
Mãe
Filho(a)
Irmão(ã)
Avô(ó)
Padastro
Madrasta
Primo(a)
Genro
Nora
Tio(a)
Sobrinho(a)
Madastra
Padastro
Cunhado(a)
Enteado(a)
Neto(a)
Bisneto(a)

*/

SELECT * FROM VISITASINTERNO

/*
- COMANDO PARA MODIFICAR O GRAU DE PARENTESCO NA TABELA VISITASINTERNO
- UTILIZAR PARA MODIFICAR TODOS OS GRAU DE PARENTESCO DAS VISITAS 

OBS.: REALIZAR ESSAS ALTERAÇÕES ANTES DE ATUALIZAR A TABELA ITENSROL.
*/

UPDATE VISITASINTERNO 
       SET ParentescoVisita='Companheiro(a)' 
       WHERE ParentescoVisita='COMPAMHEIRA' 
	   OR ParentescoVisita='COMPANEHRIA' 
	   OR ParentescoVisita='COMP'



-- COMANDO PARA ATUALIZAR A TABELA ITENSROL COM O GRAU DE PARENTESCO DA VISITA COM O INTERNO.


BEGIN TRANSACTION
UPDATE ITENSROL 
      SET ParentescoVisita=
	  (SELECT ParentescoVisita FROM VISITASINTERNO
	  WHERE VISITASINTERNO.IdVisita=ITENSROL.IdVisita)

--ROLLBACK TRANSACTION
--COMMIT TRANSACTION

-- COMANDO PARA CONSULTA O UPDATE ANTES DE RODAR O COMMIT TRANSACTION

SELECT ITENSROL.IdVisita,
       ITENSROL.ParentescoVisita,
       VISITASINTERNO.IdVisita,
	   VISITASINTERNO.ParentescoVisita
	   FROM ITENSROL
	   INNER JOIN  VISITASINTERNO
	   ON ITENSROL.IdVisita=VISITASINTERNO.IdVisita

/*
 -- PASSO A PASSO

  -- 1. RODO BEGIN TRANSACTION;
  -- 2. RODO O COMANDO, SEJA UPDATE INSERT OU DELETE;
  -- 3. RODA UM SELECT PARA VER SE ESTÁ CORRETO O COMANDO;
  -- 4. ESTANDO CORRETO O PASSO 2, RODA O COMANDO COMMIT TRANSACTION;
  -- 5. CASO O COMANDO NO PASSO 2 ESTEJA ERRADO, UTILIZO O COMANDO ROLLBACK TRANSACTION
