SELECT MOVIMENTOCRC.IdInternoCrc,
       PRONTUARIOSCRC.NomeInternoCrc,
	   MAX(MOVIMENTOCRC.DataMov)
       FROM MOVIMENTOCRC
	   INNER JOIN PRONTUARIOSCRC
	   ON MOVIMENTOCRC.IdInternoCrc=PRONTUARIOSCRC.IdInternoCrc
	   WHERE NomeOpe='Transferência da Unidade Penal'
	   AND OrigemDestino='CONJUNTO PENAL DE SERRINHA'
	   GROUP BY MOVIMENTOCRC.IdInternoCrc,
	   PRONTUARIOSCRC.NomeInternoCrc
	   ORDER BY MOVIMENTOCRC.IdInternoCrc