-- INICIO EM: 31/05/2019

-- PRORES
-- MÓDULO ENFERMARIA

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ADMISSAOENFERMEIRA') AND NAME = 'Hanseniase')
   ALTER TABLE ADMISSAOENFERMEIRA ADD Hanseniase VARCHAR(30) NULL

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ADMISSAOENFERMEIRA') AND NAME = 'Escabiose')
   ALTER TABLE ADMISSAOENFERMEIRA ADD Escabiose VARCHAR(3) NULL

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ADMISSAOENFERMEIRA') AND NAME = 'Dst')
   ALTER TABLE ADMISSAOENFERMEIRA ADD Dst VARCHAR(30) NULL

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ADMISSAOENFERMEIRA') AND NAME = 'Vacina')
   ALTER TABLE ADMISSAOENFERMEIRA ADD Vacina VARCHAR(3) NULL


IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('ACOMPANHAMENTO_INTERNO_ENFERMARIA'))
	CREATE TABLE ACOMPANHAMENTO_INTERNO_ENFERMARIA
	(
	IdEnf INT IDENTITY (1,1) PRIMARY KEY NOT NULL,	
	IdLanc INT FOREIGN KEY REFERENCES ADMISSAOENFERMEIRA(IdLanc) NOT NULL,
	IdEvoEnfer INT NULL,
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,
	DataReg DATETIME NULL,
	Diabetes VARCHAR(3) NULL,
	DiabControl VARCHAR(3) NULL,
	QtdDiabetes INT NULL,
	Hipertensao VARCHAR(3) NULL,
	HiperControl VARCHAR(3) NULL,
	QtdHipertensao INT NULL,
	Escabiose VARCHAR(3) NULL,
	EscabioseCura VARCHAR(3) NULL,
	QtdEscabiose INT NULL,
	Hanseniase VARCHAR(3) NULL,
	HanseniaseCura VARCHAR(3) NULL,
	QtdHanseniase INT NULL,
	Sifilis VARCHAR(13) NULL,
	SifilisCura VARCHAR(3) NULL,
	QtdSifilis INT NULL,
	Tuberculose VARCHAR(13) NULL,
	TuberculoseCura VARCHAR(3) NULL,
	QtdTuberculose INT NULL,
	Hiv VARCHAR(13) NULL,
	HivControlada VARCHAR(3) NULL,
	QtdHiv INT NULL,
	HepatiteB VARCHAR(13) NULL,
	HepatiteBCont VARCHAR(3) NULL,
	QtdHepatiteB INT NULL,
	HepatiteC VARCHAR(13) NULL,
	HepatiteCCont VARCHAR(3) NULL,
	QtdHepatiteC INT NULL,
	Dst VARCHAR(13) NULL,
	DstCurada VARCHAR(3) NULL,
	QtdDst INT NULL,
	Vdlr VARCHAR(13) NULL,
	VdlrCurada VARCHAR(3) NULL,
	QtdVdlr INT NULL,
	Vacina VARCHAR(3) NULL,
	VacinaCura VARCHAR(3) NULL,
	QtdVacina INT NULL,
	Observacao VARCHAR(MAX) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,	
	)
-- TERMINO DA IMPLEMENTAÇÃO DA ENFERMAGEM: 01/06/2019

-- INICIO DO MÓDULO PEDAGOGIA
-- DATA: 03/06/2019

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ITENSMATRICULA') AND NAME = 'StatusAluno')
   ALTER TABLE ITENSMATRICULA ADD StatusAluno VARCHAR(30) NULL

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ITENSMATRICULA') AND NAME = 'SituacaoAluno')
   ALTER TABLE ITENSMATRICULA ADD SituacaoAluno VARCHAR(30) NULL

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ITENSMATRICULA') AND NAME = 'DataConDes')
   ALTER TABLE ITENSMATRICULA ADD DataConDes DATETIME NULL

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ITENSMATRICULA') AND NAME = 'Observacao')
   ALTER TABLE ITENSMATRICULA ADD Observacao VARCHAR(MAX) NULL

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('EVOLUCAO_ADMISSAO_PEDAGOGIA') AND NAME = 'AcessoUni')
   ALTER TABLE EVOLUCAO_ADMISSAO_PEDAGOGIA ADD AcessoUni VARCHAR(3) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('EVOLUCAO_ADMISSAO_PEDAGOGIA') AND NAME = 'AnoIngresso')
   ALTER TABLE EVOLUCAO_ADMISSAO_PEDAGOGIA ADD AnoIngresso INT NULL

-- DATA 04-06-2019
-- RESENHA PARA REMISSÃO DE PENA

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('RESENHA_REMICAO_INTERNO'))
	CREATE TABLE RESENHA_REMICAO_INTERNO
	(
	IdResenha INT IDENTITY (1,1) PRIMARY KEY NOT NULL,	
	StatusResenha VARCHAR(20) NULL,
	DataResenha DATETIME NULL,
	IdLivro INT FOREIGN KEY REFERENCES LIVROS_REVISTAS_JORNAIS(IdLivro) NOT NULL,
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,
	IdFunc INT FOREIGN KEY REFERENCES COLABORADOR(IdFunc)NOT NULL,
	ResenhaEntregue VARCHAR(30) NULL,
	DataEntraga DATETIME NULL,
	NrResenha INT NULL,
	ValidacaoResenha REAL NULL,
	Paragrafo REAL NULL,
	Margens REAL NULL,
	Legivel REAL NULL,
	Rasuras	REAL NULL,
	Compreensao REAL NULL,
	Compatibilidade REAL NULL,
	Tema REAL NULL,
	Fidedignidade VARCHAR(MAX) NULL,
	Observacao VARCHAR(MAX) NULL,	
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,	
	)

-- TABELA DE REMIÇÃO POR INTERNO

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('ACUMULADOR_REMICAO_INTERNO'))
	CREATE TABLE ACUMULADOR_REMICAO_INTERNO
	(
	IdAcum INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	DataRegistro DATETIME NULL,
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,
	IdResenha INT FOREIGN KEY REFERENCES RESENHA_REMICAO_INTERNO(IdResenha) NOT NULL,
	DiaResenha INT NULL,
	Validacao REAL NULL,
	)
	
-- PRONTUARIO DE INTERNO CRC
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('PRONTUARIOSCRC') AND NAME = 'DocumentacaoCompleta')
   ALTER TABLE PRONTUARIOSCRC ADD DocumentacaoCompleta VARCHAR(20) NULL

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('PRONTUARIOSCRC') AND NAME = 'QuaisDocumentosFaltam')
   ALTER TABLE PRONTUARIOSCRC ADD QuaisDocumentosFaltam VARCHAR(200) NULL


-- CAPACITAÇÃO DE INTERNOS - CURSOS E OFICINAS

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('CAPACITACAO_INTERNO_TO'))
	CREATE TABLE CAPACITACAO_INTERNO_TO
	(
	IdCap INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    StatusRegistro VARCHAR(20) NULL,
	DataRegistro DATETIME NULL,
	IdCurso INT FOREIGN KEY REFERENCES CURSOS(IdCurso) NOT NULL,
	Observacao VARCHAR(MAX) NULL,	
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,	
	)


IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('ITENS_CAPACITACAO_INTERNO_TO'))
	CREATE TABLE ITENS_CAPACITACAO_INTERNO_TO
	(
	IdItemCap INT IDENTITY(1,1) PRIMARY KEY NOT NULL,    
	DataInicio DATETIME NULL,
	DataConclusao DATETIME NULL,
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,
	IdCap INT FOREIGN KEY REFERENCES CAPACITACAO_INTERNO_TO(IdCap) NOT NULL,
	SituacaoCurso VARCHAR(80) NULL,
	CargaHoraria VARCHAR(20) NULL,
	NotaAvalia REAL NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,	
	)

-- CONTROLE DE FREQUÊNCIA DOS INTERNOS QUE ESTÃO NO CURSO/OFICINA

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('FREQUENCIA_CAPACITACAO_INTERNO_TO'))
	CREATE TABLE FREQUENCIA_CAPACITACAO_INTERNO_TO
	(
	IdFreqCap INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    StatusRegistro VARCHAR(20) NULL,
	DataRegistro DATETIME NULL,
	IdCurso INT FOREIGN KEY REFERENCES CURSOS(IdCurso) NOT NULL,
	LocalCurso VARCHAR(100) NULL,
	Observacao VARCHAR(MAX) NULL,	
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,	
	)


IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('ITENS_FREQUENCIA_CAPACITACAO_INTERNO_TO'))
	CREATE TABLE ITENS_FREQUENCIA_CAPACITACAO_INTERNO_TO
	(
	IdItemFreqCap INT IDENTITY(1,1) PRIMARY KEY NOT NULL,    	
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,
	IdFreqCap INT FOREIGN KEY REFERENCES FREQUENCIA_CAPACITACAO_INTERNO_TO(IdFreqCap) NOT NULL,
	DataEntrada DATETIME NULL,
	HoraEntrada VARCHAR(20) NULL,
	HoraSaida VARCHAR(20) NULL,
	NotaAvalia REAL NULL,
	Frequencia VARCHAR(80) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,	
	)

INSERT INTO MODULOS(NomeModulo, UsuarioInsert) VALUES('DIRETORIA GERAL','ADMINISTRADOR DO SISTEMA')