INSERT INTO
STATUS_INTERNO_PSICOLOGIA(IdInternoCrc,StatusAtendimento)
SELECT DISTINCT 
EVOLUCAOPSICOLOGICA.IdInternoCrc,
EVOLUCAOPSICOLOGICA.StatusEvo 
FROM EVOLUCAOPSICOLOGICA 
INNER JOIN PRONTUARIOSCRC 
ON EVOLUCAOPSICOLOGICA.IdInternoCrc=PRONTUARIOSCRC.IdInternoCrc 
WHERE SituacaoCrc='ENTRADA NA UNIDADE' 
AND EVOLUCAOPSICOLOGICA.StatusEvo='Em Andamento'
OR SituacaoCrc='RETORNO A UNIDADE'
AND EVOLUCAOPSICOLOGICA.StatusEvo='Em Andamento'
