SELECT 
       PRODUTOS_AC.IdProd,
	   PRODUTOS_AC.DescricaoProd, 
	   SUM(QuantProd) AS Quantidade
       FROM ITENS_PAGAMENTO_KIT_INTERNOS_PRODUTOS
	   INNER JOIN PRODUTOS_AC
	   ON ITENS_PAGAMENTO_KIT_INTERNOS_PRODUTOS.IdProd=PRODUTOS_AC.IdProd
	   WHERE CONVERT(DATE, DataEntrega,103) BETWEEN '01/02/2020'
	   AND '29/02/2020' 
	   --AND PRODUTOS_AC.DescricaoProd='APARELHO DE BARBEAR DESCATAVEL'
	   GROUP BY 
	   PRODUTOS_AC.IdProd,
	   PRODUTOS_AC.DescricaoProd, 
	   QuantProd
	   ORDER BY PRODUTOS_AC.DescricaoProd