SELECT PRONTUARIOSCRC.IdInternoCrc,PRONTUARIOSCRC.NomeInternoCrc,
TEMPOFORMATIVO.DescricaoTempo,
ITENSMATRICULA.StatusAluno,
ITENSMATRICULA.SituacaoAluno,
RESENHA_REMICAO_INTERNO.ResenhaEntregue,
EVOLUCAO_ADMISSAO_PEDAGOGIA.AcessoUni
FROM PRONTUARIOSCRC
LEFT JOIN ITENSMATRICULA
ON PRONTUARIOSCRC.IdInternoCrc=ITENSMATRICULA.IdInternoCrc
LEFT JOIN MATRICULAESCOLAR
ON ITENSMATRICULA.IdMat=MATRICULAESCOLAR.IdMat
LEFT JOIN TEMPOFORMATIVO
ON MATRICULAESCOLAR.IdTempo=TEMPOFORMATIVO.IdTempo
LEFT JOIN EVOLUCAO_ADMISSAO_PEDAGOGIA
ON PRONTUARIOSCRC.IdInternoCrc=EVOLUCAO_ADMISSAO_PEDAGOGIA.IdInternoCrc
LEFT JOIN RESENHA_REMICAO_INTERNO
ON PRONTUARIOSCRC.IdInternoCrc=RESENHA_REMICAO_INTERNO.IdInternoCrc
LEFT JOIN ITENS_CAPACITACAO_INTERNO_TO
ON PRONTUARIOSCRC.IdInternoCrc=ITENS_CAPACITACAO_INTERNO_TO.IdInternoCrc
LEFT JOIN ITENS_FREQUENCIA_CAPACITACAO_INTERNO_TO
ON PRONTUARIOSCRC.IdInternoCrc=ITENS_FREQUENCIA_CAPACITACAO_INTERNO_TO.IdInternoCrc
WHERE TEMPOFORMATIVO.DescricaoTempo IS NOT NULL 
AND ITENSMATRICULA.StatusAluno IS NOT NULL
AND ITENSMATRICULA.SituacaoAluno IS NOT NULL
--AND RESENHA_REMICAO_INTERNO.ResenhaEntregue IS NOT NULL
--AND EVOLUCAO_ADMISSAO_PEDAGOGIA.AcessoUni IS NOT NULL