-- VERSÃO 6.1.0 - SISCONP

-- ORGANOGRAMADO CRIME
-- DATA: 02/10/2019

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('ORGANOGRAMA_CRIME'))
	CREATE TABLE ORGANOGRAMA_CRIME
	(
	IdOrg INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	StatusOrg VARCHAR(30) NULL,  
	DataOrg DATETIME NULL,				
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,	
	CartaBaralho VARBINARY(MAX) NULL,
	Faccao VARCHAR(200) NULL,
	IdPav INT FOREIGN KEY REFERENCES PAVILHAO(IdPav) NOT NULL,
	IdCela INT FOREIGN KEY REFERENCES CELAS(IdCela) NOT NULL,
	Recompensa REAL NULL,
	SituacaoRegistro VARCHAR(30) NULL,
	ObservacaoFrente VARCHAR(MAX) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

-- NIVEL 1

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('L1A_ORGANOGRAMA_CRIME'))
	CREATE TABLE L1A_ORGANOGRAMA_CRIME
	(
	IdL1A INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	IdOrg INT FOREIGN KEY REFERENCES ORGANOGRAMA_CRIME(IdOrg) NOT NULL,				
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,	
	CartaBaralho VARBINARY(MAX) NULL,
	Observacao VARCHAR(MAX) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('L1B_ORGANOGRAMA_CRIME'))
	CREATE TABLE L1B_ORGANOGRAMA_CRIME
	(
	IdL1B INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	IdOrg INT FOREIGN KEY REFERENCES ORGANOGRAMA_CRIME(IdOrg) NOT NULL,				
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,	
	CartaBaralho VARBINARY(MAX) NULL,	
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('L1C_ORGANOGRAMA_CRIME'))
	CREATE TABLE L1C_ORGANOGRAMA_CRIME
	(
	IdL1C INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	IdOrg INT FOREIGN KEY REFERENCES ORGANOGRAMA_CRIME(IdOrg) NOT NULL,				
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,	
	CartaBaralho VARBINARY(MAX) NULL,	
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('L1D_ORGANOGRAMA_CRIME'))
	CREATE TABLE L1D_ORGANOGRAMA_CRIME
	(
	IdL1D INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	IdOrg INT FOREIGN KEY REFERENCES ORGANOGRAMA_CRIME(IdOrg) NOT NULL,				
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,	
	CartaBaralho VARBINARY(MAX) NULL,	
	)

-- NIVEL 2

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('L2A_ORGANOGRAMA_CRIME'))
	CREATE TABLE L2A_ORGANOGRAMA_CRIME
	(
	IdL2A INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	IdOrg INT FOREIGN KEY REFERENCES ORGANOGRAMA_CRIME(IdOrg) NOT NULL,				
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,	
	CartaBaralho VARBINARY(MAX) NULL,
	Observacao VARCHAR(MAX) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('L2B_ORGANOGRAMA_CRIME'))
	CREATE TABLE L2B_ORGANOGRAMA_CRIME
	(
	IdL2B INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	IdOrg INT FOREIGN KEY REFERENCES ORGANOGRAMA_CRIME(IdOrg) NOT NULL,				
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,
	CartaBaralho VARBINARY(MAX) NULL,		
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('L2C_ORGANOGRAMA_CRIME'))
	CREATE TABLE L2C_ORGANOGRAMA_CRIME
	(
	IdL2C INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	IdOrg INT FOREIGN KEY REFERENCES ORGANOGRAMA_CRIME(IdOrg) NOT NULL,				
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,	
	CartaBaralho VARBINARY(MAX) NULL,	
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('L2D_ORGANOGRAMA_CRIME'))
	CREATE TABLE L2D_ORGANOGRAMA_CRIME
	(
	IdL2D INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	IdOrg INT FOREIGN KEY REFERENCES ORGANOGRAMA_CRIME(IdOrg) NOT NULL,				
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,	
	CartaBaralho VARBINARY(MAX) NULL,	
	)


-- TIPOS DE TRATAMENTO PSICOLOGICO

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('TIPOS_TRATAMENTO_PSICOLOGICO'))
	CREATE TABLE TIPOS_TRATAMENTO_PSICOLOGICO
	(
	IdTipo INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	StatusTipo VARCHAR(7) NULL,
	DataTipo DATETIME NULL,
	DescricaoTipo VARCHAR(300) NULL,
	Texto VARCHAR(MAX) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioUp VARCHAR(10) NULL,	
	)

-- TRATAMENTO

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('TRATAMENTO_PSICOLOGICO'))
	CREATE TABLE TRATAMENTO_PSICOLOGICO
	(
	IdTRAT INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	StatusTrat VARCHAR(7) NULL,
	DataTrat DATETIME NULL,
	IdTipo INT FOREIGN KEY REFERENCES TIPOS_TRATAMENTO_PSICOLOGICO(IdTipo) NOT NULL,
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,	
	ID_REGISTRO_ATEND_EVOL INT NOT NULL,
	DataInicio DATETIME NULL,
	DataTermino DATETIME NULL,
	TextoTratamento VARCHAR(MAX) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioUp VARCHAR(10) NULL,	
	)
