/*
DATA: 05/04/2021
AUTOR: RONALDO ALVES DA SILVA
VERSÃO: 6.3.4.2021
*/

-- CANCELAMENTO DE EVASÃO DE INTERNOS

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('CANCELAMENTO_EVASAO_INTERNOS'))
	CREATE TABLE CANCELAMENTO_EVASAO_INTERNOS
	(
	IdCancelaEvasao INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	StatusRegistro VARCHAR(30) NULL,
	DataRegistro DATETIME NULL,
	TipoOperacaoCancelar INT NULL,
	NomeResponsavel VARCHAR(200) NULL,
	CargoResponsavel VARCHAR(100) NULL,
	NumeroDocumentoCancela VARCHAR(100) NULL,
	DataCancelamento DATETIME NULL,
	IdLanc INT FOREIGN KEY REFERENCES EVADIDOSIND(IdLanc) NOT NULL,
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,
	MotivoCancelamento VARCHAR(MAX) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)
