SELECT ITENSROL.IdRol,ROLVISITAS.StatusRol,
       ITENSROL.IdInternoCrc,
       PRONTUARIOSCRC.NomeInternoCrc,
	   DADOSPENAISINTERNOS.Regime, 
       CELAS.IdPav, 
       PAVILHAO.DescricaoPav,
	   ITENSROL.IdVisita,
	   VISITASINTERNO.NomeVisita,
       ITENSROL.StatusVisita,
	   VISITASINTERNO.ImagemVisita, 
       ITENSROL.ParentescoVisita, 
       VISITASINTERNO.BiometriaDedo1, 
       VISITASINTERNO.BiometriaDedo2, 
       VISITASINTERNO.BiometriaDedo3, 
       VISITASINTERNO.BiometriaDedo4, 
       VISITASINTERNO.ImagemFrenteVI	    
	   FROM ITENSROL 
       INNER JOIN VISITASINTERNO 
       ON VISITASINTERNO.IdVisita=ITENSROL.IdVisita 
       INNER JOIN ROLVISITAS 
       ON ITENSROL.IdRol=ROLVISITAS.IdRol 
       INNER JOIN PRONTUARIOSCRC 
       ON ROLVISITAS.IdInternoCrc=PRONTUARIOSCRC.IdInternoCrc 
       INNER JOIN DADOSPENAISINTERNOS 
       ON PRONTUARIOSCRC.IdInternoCrc=DADOSPENAISINTERNOS.IdInternoCrc 
       INNER JOIN ITENSLOCACAOINTERNO 
       ON PRONTUARIOSCRC.IdInternoCrc=ITENSLOCACAOINTERNO.IdInternoCrc 
       INNER JOIN CELAS ON ITENSLOCACAOINTERNO.IdCela=CELAS.IdCela 
       INNER JOIN PAVILHAO ON CELAS.IdPav=PAVILHAO.IdPav 
	   WHERE ITENSROL.IdVisita=143
       AND ITENSROL.StatusVisita='Ativo'
	   AND ROLVISITAS.StatusRol='ABERTO'
	   ORDER BY PRONTUARIOSCRC.NomeInternoCrc