/*
DATA: 29/07/2020
AUTOR: RONALDO ALVES DA SILVA
VERSÃO: 6.2.0
*/

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('CANCELAR_PAGAMENTO_KIT_HIGIENE'))
	CREATE TABLE CANCELAR_PAGAMENTO_KIT_HIGIENE
	(
	IdRegistro INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	StatusRegistro VARCHAR(30) NULL,
	DataRegistro DATETIME NULL,
	IdPav INT FOREIGN KEY REFERENCES PAVILHAO(IdPav) NOT NULL,
	IdCela INT FOREIGN KEY REFERENCES CELAS(IdCela) NOT NULL,
	TipoKit VARCHAR(100) NULL,
	IdRegistroKit INT NULL,
	DataRegistroKit DATETIME NULL,
	MotivoCancelamento VARCHAR(MAX) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)
	
IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('ITENS_CANCELAR_PAGAMENTO_KIT_HIGIENE'))
	CREATE TABLE ITENS_CANCELAR_PAGAMENTO_KIT_HIGIENE
	(
	IdItemSA INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	IdRegistro INT FOREIGN KEY REFERENCES CANCELAR_PAGAMENTO_KIT_HIGIENE(IdRegistro) NOT NULL,
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,
	IdProd INT FOREIGN KEY REFERENCES PRODUTOS_AC(IdProd) NOT NULL,
	Quantidade INT NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)