SELECT FREQUENCIA_CAPACITACAO_INTERNO_TO.IdFreqCap,FREQUENCIA_CAPACITACAO_INTERNO_TO.DataRegistro, 
       FREQUENCIA_CAPACITACAO_INTERNO_TO.IdCurso,
	   CURSOS.DescricaoCurso,
	   ITENS_FREQUENCIA_CAPACITACAO_INTERNO_TO.IdInternoCrc,
	   ITENS_FREQUENCIA_CAPACITACAO_INTERNO_TO.DataEntrada
       FROM ITENS_FREQUENCIA_CAPACITACAO_INTERNO_TO 
                 INNER JOIN PRONTUARIOSCRC 
                 ON ITENS_FREQUENCIA_CAPACITACAO_INTERNO_TO.IdInternoCrc=PRONTUARIOSCRC.IdInternoCrc 
                 INNER JOIN FREQUENCIA_CAPACITACAO_INTERNO_TO 
                 ON ITENS_FREQUENCIA_CAPACITACAO_INTERNO_TO.IdFreqCap=FREQUENCIA_CAPACITACAO_INTERNO_TO.IdFreqCap 
				 INNER JOIN CURSOS
				 ON FREQUENCIA_CAPACITACAO_INTERNO_TO.IdCurso=CURSOS.IdCurso
                 AND CONVERT(DATE, DataEntrada) BETWEEN'01/02/2020'
                 AND '29/02/2020'