SELECT * 
FROM (
SELECT --PRODUTOS_AC.IdProd AS COD,
		DescricaoProd AS DESCRICAO,
		SUM(QuantProd) AS TOTAL_ENTREGUE
		FROM 
		COMPOSICAO_PAGAMENTO_KIT_INTERNOS_LOTE
		INNER JOIN ITENS_PRODUTOS_INTERNOS_PAVILHAO_KIT_LOTE
		ON COMPOSICAO_PAGAMENTO_KIT_INTERNOS_LOTE.IdRegistroComp=ITENS_PRODUTOS_INTERNOS_PAVILHAO_KIT_LOTE.IdRegistroComp
		INNER JOIN PRODUTOS_AC 
		ON ITENS_PRODUTOS_INTERNOS_PAVILHAO_KIT_LOTE.IdProd=PRODUTOS_AC.IdProd
		WHERE CONVERT(DATE, DataComp) BETWEEN '01/02/2020' AND '29/02/2020'
		--AND PRODUTOS_AC.IdProd = 7
		GROUP BY PRODUTOS_AC.IdProd,PRODUTOS_AC.DescricaoProd
		--ORDER BY PRODUTOS_AC.DescricaoProd
		) linhas 
		PIVOT (SUM(TOTAL_ENTREGUE) FOR DESCRICAO IN (
		[APARELHO DE BARBEAR DESCATAVEL],
		[BERMUDA LARANJA G],
		[CAMISA LARANJA G],
		[CANECA PLASTICA C ALCA 300ML],
		[COBERTOR DORME BEM],
		[COLCHAO DE SOLTEIRO],
		[COLHER PLASTICA],
		[CREME DENTAL 90G],
		[CUECA DE MALHA],
		[DESODORANTE EM CREME],
		[ESCOVA DENTAL],
		[LENCOL DE SOLTEIRO],
		[PAPEL HIGIENICO 30MTS],
		[POTE PLASTICO 1.200L],
		[SABAO EM PO 200G],
		[SABONETE 90G],
		[SANDALIA TAM. 37 - 43],
		[TOALHA DE BANHO])) Colunas