-- SCRIPT DE VERSÃO SISCONP 6.0
-- DATA: 18/08/2019

-- EVOLUÇÃO ATENDIMENTO FAMILIA

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('EVOLUCAO_ATENDIMENTO_FAMILIA'))
	CREATE TABLE EVOLUCAO_ATENDIMENTO_FAMILIA
	(
	IdEvolucaoFam INT IDENTITY(1,1) PRIMARY KEY NOT NULL,   	
	DataEvolVisita DATETIME NULL, 	
	IdVisita INT FOREIGN KEY REFERENCES VISITASINTERNO(IdVisita) NOT NULL,
	IdAtendf INT FOREIGN KEY REFERENCES ATENDIMENTOFAMILIAR(IdAtendf) NOT NULL,	
	TextoEvolucaoVisita VARCHAR(MAX) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,	
	)

-- CAMPOS PARA O ATENDIMENTO FAMILIA

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'ReconhecerPaternidade')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD ReconhecerPaternidade VARCHAR(15) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'AuxilioReclusao')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD AuxilioReclusao VARCHAR(15) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'OutroBerneficio')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD OutroBerneficio VARCHAR(60) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'PossuiFilhos')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD PossuiFilhos VARCHAR(25) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'QuantidadeFilhos')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD QuantidadeFilhos INT
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'QualIdade')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD QualIdade VARCHAR(25) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'Estudam')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD Estudam VARCHAR(25) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'TipoEscola')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD TipoEscola VARCHAR(60) NULL
--IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'Estudam')
  -- ALTER TABLE ATENDIMENTOFAMILIAR ADD Estudam VARCHAR(25) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'ParticipaProjeto')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD ParticipaProjeto VARCHAR(MAX) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'Endereco')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD Endereco VARCHAR(150) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'Cidade')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD Cidade VARCHAR(100) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'Estado')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD Estado VARCHAR(60) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'Telefone1')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD Telefone1 VARCHAR(100) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'Telefone2')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD Telefone2 VARCHAR(100) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'Celular')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD Celular VARCHAR(100) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'Trabalha')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD Trabalha VARCHAR(100) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'Escolaridade')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD Escolaridade VARCHAR(100) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'ProblemaSaude')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD ProblemaSaude VARCHAR(100) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'QualProblemaSaude')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD QualProblemaSaude VARCHAR(100) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'UsoMedicacao')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD UsoMedicacao VARCHAR(100) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'QuaisMedicacoes')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD QuaisMedicacoes VARCHAR(60) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'DoencaPermanente')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD DoencaPermanente VARCHAR(60) NULL
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ATENDIMENTOFAMILIAR') AND NAME = 'QuaisDoencas')
   ALTER TABLE ATENDIMENTOFAMILIAR ADD QuaisDoencas VARCHAR(100) NULL 

-- CADASTRO DE ADVOGADO

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ADVOGADOS') AND NAME = 'NomeMae')
   ALTER TABLE ADVOGADOS ADD NomeMae VARCHAR(200) NULL 
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ADVOGADOS') AND NAME = 'NomePai')
   ALTER TABLE ADVOGADOS ADD NomePai VARCHAR(200) NULL 
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ADVOGADOS') AND NAME = 'SituacaoCadastral')
   ALTER TABLE ADVOGADOS ADD SituacaoCadastral VARCHAR(100) NULL 
IF EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ADVOGADOS') AND NAME = 'ObsAdvogado')   
   ALTER TABLE ADVOGADOS ALTER COLUMN ObsAdvogado VARCHAR(MAX)

-- VISITAS DIVERSAS

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('VISITASDIVERSAS') AND NAME = 'NomeMae')
   ALTER TABLE VISITASDIVERSAS ADD NomeMae VARCHAR(200) NULL 
IF EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('VISITASDIVERSAS') AND NAME = 'ObsVisita')   
   ALTER TABLE ADVOGADOS ALTER COLUMN ObsVisita VARCHAR(MAX)
-- OFICIAL DE JUSTIÇA

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('OFICIAL_JUSTICA') AND NAME = 'NomeMae')
   ALTER TABLE OFICIAL_JUSTICA ADD NomeMae VARCHAR(200) NULL
IF EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('OFICIAL_JUSTICA') AND NAME = 'ObsOficial')   
   ALTER TABLE ADVOGADOS ALTER COLUMN ObsOficial VARCHAR(MAX)

-- TABELA DE INFORMAÇÕES DE ATENDIMENTO DO INTERNO NO PSP

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('ATENDIMENTO_PSP_INTERNO_TV'))
	CREATE TABLE ATENDIMENTO_PSP_INTERNO_TV
	(
	IdAPIT INT IDENTITY(1,1) PRIMARY KEY NOT NULL,   			
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,
	IdDepartamento INT FOREIGN KEY REFERENCES DEPARTAMENTOS(IdDepartamento) NOT NULL,	
	IdRegistro INT FOREIGN KEY REFERENCES REGISTRO_ATENDIMENTO_INTERNO_PSP(IdRegistro) NOT NULL,
	Atendendo VARCHAR(3) NULL,
	UsuarioAtendente VARCHAR(50) NULL,	
	DataAtendimento VARCHAR(20) NULL,
	HorarioInicio VARCHAR(10) NULL,
	HorarioTermino VARCHAR(20) NULL,
	Concluido VARCHAR(3) NULL,
	IdAdentimento INT NULL,
	TipoAtendimento VARCHAR(80) NULL,
	)

-- ADICIONADO CAMPO POR CAUSA DA ASSINATURA BIOMETRIA E TELA DE TV ATENDIMENTO

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('REGISTRO_ATENDIMENTO_INTERNO_PSP') AND NAME = 'UsuarioAtendente')
   ALTER TABLE REGISTRO_ATENDIMENTO_INTERNO_PSP ADD UsuarioAtendente VARCHAR(200) NULL
