/* VERSÃO 6.1.2
 DATA: 05/06/2020

*/

-- ADICIONAR CAMPO NA TABELA DE CANCELAMENTO DE RETORNOS ITENS_REGISTRO_CANCELADO_RETORNOS

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('ITENS_REGISTRO_CANCELADO_RETORNOS') AND NAME = 'TipoRetorno')
           ALTER TABLE ITENS_REGISTRO_CANCELADO_RETORNOS ADD TipoRetorno VARCHAR(80) NULL