/*
SELECT * FROM OPERACAO WHERE TipoOp='Saídas'
SELECT DataPopMov,TotalGeralInternos,HorarioInsert FROM MOVPOPULACAO 
SELECT * FROM ITENSNOVAENTRADA
SELECT * FROM ITENSENTRADA
SELECT * FROM ITENSENTRADAPORTARIA
SELECT * FROM POPULACAOINTERNOS_CRC
*/
/*
 TABELA DE IPOS DE OPERAÇÃO
*/
SELECT * FROM OPERACAO WHERE TipoOp='Saídas'
/*
 TABELA DE POPULAÇÃO
*/
SELECT DataPopMov,TotalGeralInternos,HorarioInsert FROM MOVPOPULACAO
/* 
SAIDA DE INTERNOS DA UNIDADE
*/
SELECT DataSaida,DestinoSaida,HoraSaida 
       FROM ITENSREGSAIDA 
       WHERE DataSaida BETWEEN '2020/04/01' 
	   AND '2020/04/14'	   
	   AND DestinoSaida='SAIDA ALVARA'
	   OR DataSaida BETWEEN '2020/04/01' 
	   AND '2020/04/14'
	   AND DestinoSaida='SAIDA LIVRAMENTO CONDICIONAL'
	   OR DataSaida BETWEEN '2020/04/01' 
	   AND '2020/04/14'
	   AND DestinoSaida='TRANSFERENCIA'
	   OR DataSaida BETWEEN '2020/04/01' 
	   AND '2020/04/14'
	   AND DestinoSaida='SAIDA PROGRESSAO DE REGIME'
	   OR DataSaida BETWEEN '2020/04/01' 
	   AND '2020/04/14'
	   AND DestinoSaida='FUGA DA UNIDADE'
	   OR DataSaida BETWEEN '2020/04/01' 
	   AND '2020/04/14'
	   AND DestinoSaida='EVASAO'
	   OR DataSaida BETWEEN '2020/04/01' 
	   AND '2020/04/14'
	   AND DestinoSaida='OBITO'
	   OR DataSaida BETWEEN '2020/04/01' 
	   AND '2020/04/14'
	   AND DestinoSaida='PRISAO DOMICILIAR - COVID-19'
	   OR DataSaida BETWEEN '2020/04/01' 
	   AND '2020/04/14'
	   AND DestinoSaida='SAIDA TEMPORARIA'
	   ORDER BY DataSaida,HoraSaida
/*
  NOVA ENTRADA NA UNIDADE
*/
SELECT * FROM ITENSNOVAENTRADA
         WHERE DataEntrada BETWEEN '2020/04/01' 
	     AND '2020/04/14'
/*		 	
  ENTRA PELA PRIMEIRA VEZ
*/
SELECT DataEntrada,HoraEntrada FROM ITENSENTRADAPORTARIA
         WHERE DataEntrada BETWEEN '2020/04/01' 
	     AND '2020/04/14'
		 ORDER BY DataEntrada,HoraEntrada