-- VERSÃO 6.0.2 - SISCONP

-- ESCOLTA DE INTERNOS PARA PSP
-- DATA: 11/09/2019

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('ESCOLTA_INTERNO_PSP'))
	CREATE TABLE ESCOLTA_INTERNO_PSP
	(
	IdEsco INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	StatusEscolta VARCHAR(30) NULL,  
	DataRegistro DATETIME NULL,			
	IdFunc INT FOREIGN KEY REFERENCES COLABORADOR(IdFunc) NOT NULL,
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,	
	DataSaida DATETIME NULL,
	HoraSaida VARCHAR(20) NULL,
	DataRetorno DATETIME NULL,
	HoraRetorno VARCHAR(20) NULL, 
	AssinaturaColaboradorSaida VARBINARY(MAX) NULL,
	AssinaturaColaboradorRetorno VARBINARY(MAX) NULL,
	AssinaturaInternoSaida VARBINARY(MAX) NULL,
	AssinaturaInternoRetorno VARBINARY(MAX) NULL,
	AssinaturaColaboradorLiberadorSaida VARBINARY(MAX) NULL,
	AssinaturaColaboradorLiberadorRetorno VARBINARY(MAX) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

-- LIBERADOR DA PASSAGEM DO INTERNO NA BASE PARA O PSP

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('LIBERADOR_ESCOLTA_INTERNO_PSP'))
	CREATE TABLE LIBERADOR_ESCOLTA_INTERNO_PSP
	(
	IdLibe INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	StatusLibera VARCHAR(30) NULL,  
	DataRegistro DATETIME NULL,			
	IdPav INT FOREIGN KEY REFERENCES PAVILHAO(IdPav) NOT NULL,	
	Observacao VARCHAR(MAX) NULL,
	UsuarioInsert VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('ITENS_LIBERADOR_ESCOLTA_INTERNO_PSP'))
	CREATE TABLE ITENS_LIBERADOR_ESCOLTA_INTERNO_PSP
	(
	IdItemLibPSP INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	IdLibe INT FOREIGN KEY REFERENCES LIBERADOR_ESCOLTA_INTERNO_PSP(IdLibe) NOT NULL,
	IdFunc INT FOREIGN KEY REFERENCES COLABORADOR(IdFunc) NOT NULL,
	StatusFunc VARCHAR(30) NULL,  
	UsuarioInsert VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('DEPOSITO_INATIVOS') AND NAME = 'Tipo')
   ALTER TABLE DEPOSITO_INATIVOS ADD Tipo VARCHAR(5) NULL