CREATE TRIGGER TGR_STP_INS
ON EVOLUCAOPSICOLOGIA
FOR DELETE
AS
BEGIN
    DECLARE
    @STATUS_ATEND  VARCHAR(15),
	@CODIGO_INTERNO INT
 
    SELECT @STATUS_ATEND = StatusAtendimento FROM DELETED
 
    UPDATE STATUS_INTERNO_PSICOLOGIA SET StatusAtendimento = @STATUS_ATEND
    WHERE IdInternoCrc = @CODIGO_INTERNO
END
GO