-- ABRIR BANCO DE DESTINO
USE DB_SOCIALIZA_CPBA
-- COMANDO PARA CONFIRMAR 
BEGIN TRANSACTION
UPDATE PRONTUARIOSCRC1
          SET PRONTUARIOSCRC1.SituacaoCrc = PRONTUARIOSCRC2.SituacaoCrc
          FROM DB_SOCIALIZA_CPBA..PRONTUARIOSCRC PRONTUARIOSCRC1 
          INNER JOIN DB_SOCIALIZA_CPBA_TESTE..PRONTUARIOSCRC PRONTUARIOSCRC2
          ON PRONTUARIOSCRC1.IdInternoCrc = PRONTUARIOSCRC2.IdInternoCrc

  -- COMANDO PARA DESFAZER O UPDATE, INSERT OU DELETE
ROLLBACK TRANSACTION
  -- CONFIRMAR COMANDO DE UPDATE, INSERT OU DELETE, NÃO PODE SER MAIS REVERTIDO.
  -- SEMPRE MANTER O COMANDO ROLLBACK E  COMMIT COMENTADO.
COMMIT TRANSACTION


  -- PASSO A PASSO

  -- 1. RODO BEGIN TRANSACTION;
  -- 2. RODO O COMANDO, SEJA UPDATE INSERT OU DELETE;
  -- 3. RODA UM SELECT PARA VER SE ESTÁ CORRETO O COMANDO;
  -- 4. ESTANDO CORRETO O PASSO 2, RODA O COMANDO COMMIT TRANSACTION;
  -- 5. CASO O COMANDO NO PASSO 2 ESTEJA ERRADO, UTILIZO O COMANDO ROLLBACK TRANSACTION
