
--ADICIONAR CAMPO PARA VERIRIFICAR SE O INTERNO TEM OU NÃO BIOMETRIA CADASTRADA
IF NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('PRONTUARIOSCRC') AND NAME = 'BiometriaInternos')
   ALTER TABLE PRONTUARIOSCRC ADD BiometriaInternos VARCHAR(13) NULL

-- EXPORTAR OS DADOS DA TABELA BIOMETRIA_INTERNOS PARA PRONTUARIOSCRC

UPDATE PRONTUARIOSCRC SET BiometriaInternos=(SELECT IdInternoCrc FROM BIOMETRIA_INTERNOS WHERE PRONTUARIOSCRC.IdInternoCrc=BIOMETRIA_INTERNOS.IdInternoCrc)