/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Util.Produtividade;

import gestor.Controle.ControleListaTecnicosProdutividadePSP;
import gestor.Controle.converterDataStringDataDate;
import gestor.Dao.ConexaoBancoDados;
import gestor.Dao.ModeloTabela;
import gestor.Modelo.RegistroAtendimentoInternos;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronaldo.silva7
 */
public class Produtividade extends javax.swing.JFrame {

    ConexaoBancoDados conecta = new ConexaoBancoDados();
    ControleListaTecnicosProdutividadePSP control = new ControleListaTecnicosProdutividadePSP();
    converterDataStringDataDate convertedata = new converterDataStringDataDate();

    String dataEvolucao;
    public static int qtdTecnicosPSP = 0;
    SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss"); // HORAIO DE 24 HORAS, PARA O DE 12 HORAS UTILIZAR hh:mm:ss
    SimpleDateFormat formatter2 = new SimpleDateFormat("dd/MM/yyyy");
    public static String qtd;

    //ConexaoDB con = new ConexaoDB();
    /**
     * Creates new form DisplayProdutividade
     */
    public Produtividade() {
        initComponents();
        mostrarDemostrativoPSP();
        setExtendedState(MAXIMIZED_BOTH); // Maximnizar a tela prinicpal
        Thread threadRelogio = new Thread() {

            @Override
            public void run() {
                rodaRelogio();
            }
        };
        threadRelogio.start();

        Date data = new Date();
        String hora = formatter.format(data); // Data da conexão
        String date = formatter2.format(data); // Hora da conexão

        jHoraSistemaPSP.setText(String.valueOf(hora));    // no lugar do label, por seu JTextField    
        jDataSistemaPSP.setText(String.valueOf(date));
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); //Impedir que a janela seja fechada pelo X    
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (e.getID() == WindowEvent.WINDOW_CLOSING) {
                    int selectedOption = JOptionPane.showConfirmDialog(null, "Deseja realmente sair da Tela?", "Sistema informa:", JOptionPane.YES_NO_OPTION);
                    if (selectedOption == JOptionPane.YES_OPTION) {
                        dispose();
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCabecalho = new javax.swing.JPanel();
        jLabelCabecalho = new javax.swing.JLabel();
        jLabelLogoSocializa = new javax.swing.JLabel();
        jLabelLogoSisconp = new javax.swing.JLabel();
        jPanelTituloTela = new javax.swing.JPanel();
        RotulojPanel = new javax.swing.JPanel();
        jPanelDataTecSet = new javax.swing.JPanel();
        jPanelData = new javax.swing.JPanel();
        jLabelData = new javax.swing.JLabel();
        jPanelTecnico = new javax.swing.JPanel();
        jLabelTecnico = new javax.swing.JLabel();
        jPanelTSstDiaSemMes = new javax.swing.JPanel();
        jPanelSetor = new javax.swing.JPanel();
        jLabelSetor = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelSetor1 = new javax.swing.JPanel();
        jLabelSetor1 = new javax.swing.JLabel();
        jPanelSetor2 = new javax.swing.JPanel();
        jLabelSetor2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelTabela = new javax.swing.JPanel();
        jScrollPaneTabela = new javax.swing.JScrollPane();
        jTabelaAtendimentoProdutivida = new javax.swing.JTable();
        jPanelRodape = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jHoraSistemaPSP = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jDataSistemaPSP = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sysconp");
        setBackground(new java.awt.Color(0, 153, 204));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/gestor/Imagens/FavonIconJFrame100.png")));

        jPanelCabecalho.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCabecalho.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelCabecalho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCabecalho.setText("DEMONSTRATIVO DE ATENDIMENTO E PRODUTIVIDADE");

        jLabelLogoSocializa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/logoSocializa200.jpg"))); // NOI18N

        jLabelLogoSisconp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoSisconp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/ICONE70.png"))); // NOI18N

        javax.swing.GroupLayout jPanelCabecalhoLayout = new javax.swing.GroupLayout(jPanelCabecalho);
        jPanelCabecalho.setLayout(jPanelCabecalhoLayout);
        jPanelCabecalhoLayout.setHorizontalGroup(
            jPanelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCabecalhoLayout.createSequentialGroup()
                .addComponent(jLabelLogoSocializa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogoSisconp, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCabecalhoLayout.setVerticalGroup(
            jPanelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogoSocializa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelCabecalhoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelCabecalho)
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jLabelLogoSisconp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelTituloTela.setBackground(new java.awt.Color(0, 153, 204));
        jPanelTituloTela.setLayout(new java.awt.BorderLayout());

        RotulojPanel.setLayout(new javax.swing.BoxLayout(RotulojPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanelDataTecSet.setPreferredSize(new java.awt.Dimension(99, 80));
        jPanelDataTecSet.setLayout(new java.awt.BorderLayout());

        jPanelData.setMinimumSize(new java.awt.Dimension(150, 44));
        jPanelData.setLayout(new java.awt.BorderLayout());

        jLabelData.setBackground(new java.awt.Color(51, 51, 0));
        jLabelData.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("     DATA     ");
        jLabelData.setOpaque(true);
        jPanelData.add(jLabelData, java.awt.BorderLayout.CENTER);

        jPanelDataTecSet.add(jPanelData, java.awt.BorderLayout.LINE_START);

        jPanelTecnico.setLayout(new java.awt.BorderLayout());

        jLabelTecnico.setBackground(new java.awt.Color(0, 153, 153));
        jLabelTecnico.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTecnico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTecnico.setText("TÉCNICO");
        jLabelTecnico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTecnico.setMinimumSize(new java.awt.Dimension(150, 44));
        jLabelTecnico.setOpaque(true);
        jPanelTecnico.add(jLabelTecnico, java.awt.BorderLayout.CENTER);

        jPanelDataTecSet.add(jPanelTecnico, java.awt.BorderLayout.CENTER);

        RotulojPanel.add(jPanelDataTecSet);

        jPanelTSstDiaSemMes.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTSstDiaSemMes.setLayout(new java.awt.BorderLayout());

        jPanelSetor.setMinimumSize(new java.awt.Dimension(150, 44));
        jPanelSetor.setLayout(new java.awt.BorderLayout());

        jLabelSetor.setBackground(new java.awt.Color(51, 0, 51));
        jLabelSetor.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelSetor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSetor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSetor.setText("          SETOR          ");
        jLabelSetor.setOpaque(true);
        jPanelSetor.add(jLabelSetor, java.awt.BorderLayout.CENTER);

        jPanelTSstDiaSemMes.add(jPanelSetor, java.awt.BorderLayout.LINE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(1, 80));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanelSetor1.setMinimumSize(new java.awt.Dimension(150, 44));
        jPanelSetor1.setLayout(new java.awt.BorderLayout());

        jLabelSetor1.setBackground(new java.awt.Color(255, 153, 0));
        jLabelSetor1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelSetor1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSetor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSetor1.setText("DIÁRIO");
        jLabelSetor1.setOpaque(true);
        jPanelSetor1.add(jLabelSetor1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelSetor1);

        jPanelSetor2.setMinimumSize(new java.awt.Dimension(150, 44));
        jPanelSetor2.setLayout(new java.awt.BorderLayout());

        jLabelSetor2.setBackground(new java.awt.Color(0, 51, 51));
        jLabelSetor2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelSetor2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSetor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSetor2.setText("SEMANAL");
        jLabelSetor2.setToolTipText("");
        jLabelSetor2.setOpaque(true);
        jPanelSetor2.add(jLabelSetor2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelSetor2);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENSAL");
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanelTSstDiaSemMes.add(jPanel1, java.awt.BorderLayout.CENTER);

        RotulojPanel.add(jPanelTSstDiaSemMes);

        jPanelTituloTela.add(RotulojPanel, java.awt.BorderLayout.NORTH);

        jPanelTabela.setBackground(new java.awt.Color(0, 153, 204));
        jPanelTabela.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTabela.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTabela.setLayout(new java.awt.BorderLayout());

        jTabelaAtendimentoProdutivida.setAutoCreateRowSorter(true);
        jTabelaAtendimentoProdutivida.setBackground(new java.awt.Color(255, 255, 204));
        jTabelaAtendimentoProdutivida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTabelaAtendimentoProdutivida.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jTabelaAtendimentoProdutivida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", ""
            }
        ));
        jTabelaAtendimentoProdutivida.setRowHeight(35);
        jScrollPaneTabela.setViewportView(jTabelaAtendimentoProdutivida);
        if (jTabelaAtendimentoProdutivida.getColumnModel().getColumnCount() > 0) {
            jTabelaAtendimentoProdutivida.getColumnModel().getColumn(0).setPreferredWidth(105);
            jTabelaAtendimentoProdutivida.getColumnModel().getColumn(1).setPreferredWidth(535);
            jTabelaAtendimentoProdutivida.getColumnModel().getColumn(2).setPreferredWidth(240);
            jTabelaAtendimentoProdutivida.getColumnModel().getColumn(3).setPreferredWidth(127);
            jTabelaAtendimentoProdutivida.getColumnModel().getColumn(4).setPreferredWidth(153);
            jTabelaAtendimentoProdutivida.getColumnModel().getColumn(5).setPreferredWidth(140);
        }

        jPanelTabela.add(jScrollPaneTabela, java.awt.BorderLayout.CENTER);

        jPanelTituloTela.add(jPanelTabela, java.awt.BorderLayout.CENTER);

        jPanelRodape.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRodape.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelRodape.setPreferredSize(new java.awt.Dimension(603, 77));

        jPanel17.setBackground(new java.awt.Color(0, 102, 102));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.setForeground(new java.awt.Color(0, 0, 153));
        jPanel17.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hora:");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(0, 102, 102));
        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel18.setForeground(new java.awt.Color(0, 0, 153));
        jPanel18.setToolTipText("");

        jHoraSistemaPSP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jHoraSistemaPSP.setForeground(new java.awt.Color(255, 255, 255));
        jHoraSistemaPSP.setText("00:00:00");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHoraSistemaPSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHoraSistemaPSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.setBackground(new java.awt.Color(0, 102, 102));
        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel20.setForeground(new java.awt.Color(0, 0, 153));
        jPanel20.setToolTipText("");
        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Data:");
        jPanel20.add(jLabel15, java.awt.BorderLayout.CENTER);

        jPanel21.setBackground(new java.awt.Color(0, 102, 102));
        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel21.setForeground(new java.awt.Color(0, 0, 153));
        jPanel21.setToolTipText("");

        jDataSistemaPSP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDataSistemaPSP.setForeground(new java.awt.Color(255, 255, 255));
        jDataSistemaPSP.setText("dd/mm/aa");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDataSistemaPSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDataSistemaPSP)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(240, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/Button_Refresh_Icon_32.png"))); // NOI18N
        jButton1.setText("Atualizar");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indicadores de Meta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelRodapeLayout = new javax.swing.GroupLayout(jPanelRodape);
        jPanelRodape.setLayout(jPanelRodapeLayout);
        jPanelRodapeLayout.setHorizontalGroup(
            jPanelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRodapeLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelRodapeLayout.setVerticalGroup(
            jPanelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRodapeLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRodapeLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelRodapeLayout.createSequentialGroup()
                        .addGroup(jPanelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRodapeLayout.createSequentialGroup()
                                .addGroup(jPanelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5))))
        );

        jPanelTituloTela.add(jPanelRodape, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTituloTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanelTituloTela, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mostrarDemostrativoPSP();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RotulojPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jDataSistemaPSP;
    private javax.swing.JLabel jHoraSistemaPSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCabecalho;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelLogoSisconp;
    private javax.swing.JLabel jLabelLogoSocializa;
    private javax.swing.JLabel jLabelSetor;
    private javax.swing.JLabel jLabelSetor1;
    private javax.swing.JLabel jLabelSetor2;
    private javax.swing.JLabel jLabelTecnico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCabecalho;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JPanel jPanelDataTecSet;
    private javax.swing.JPanel jPanelRodape;
    private javax.swing.JPanel jPanelSetor;
    private javax.swing.JPanel jPanelSetor1;
    private javax.swing.JPanel jPanelSetor2;
    private javax.swing.JPanel jPanelTSstDiaSemMes;
    private javax.swing.JPanel jPanelTabela;
    private javax.swing.JPanel jPanelTecnico;
    private javax.swing.JPanel jPanelTituloTela;
    private javax.swing.JScrollPane jScrollPaneTabela;
    private javax.swing.JTable jTabelaAtendimentoProdutivida;
    // End of variables declaration//GEN-END:variables

//    public void preencherTabelaProdutividade(String sql) {
//        ArrayList dados = new ArrayList();
//        String[] Colunas = new String[]{"Colaborador", "Departamento"};
//        conecta.abrirConexao();
//        try {
//            conecta.executaSQL(sql);
//            conecta.rs.first();
//            do {
//                // Formatar a data Entrada
////                dataEvolucao = conecta.rs.getString("DataReg");
////                String diae = dataEvolucao.substring(8, 10);
////                String mese = dataEvolucao.substring(5, 7);
////                String anoe = dataEvolucao.substring(0, 4);
////                dataEvolucao = diae + "/" + mese + "/" + anoe;
//                dados.add(new Object[]{conecta.rs.getString("NomeFunc"), conecta.rs.getString("NomeDepartamento"), conecta.rs.getInt("Qtd")});
//            } while (conecta.rs.next());
//        } catch (SQLException ex) {
//        }
//        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
//        jTabelaAtendimentoProdutivida.setModel(modelo);
//        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(0).setPreferredWidth(220);
//        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(0).setResizable(false);
//        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(1).setPreferredWidth(220);
//        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(1).setResizable(false);
//        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(2).setPreferredWidth(390);
//        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(2).setResizable(false);
//        jTabelaAtendimentoProdutivida.getTableHeader().setReorderingAllowed(false);
//        jTabelaAtendimentoProdutivida.setAutoResizeMode(jTabelaAtendimentoProdutivida.AUTO_RESIZE_OFF);
//        jTabelaAtendimentoProdutivida.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//        alinharCamposTabelaEvolucao();
//        conecta.desconecta();
//    }
    public void alinharCamposTabelaEvolucao() {
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        //
        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(1).setCellRenderer(centralizado);
        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(2).setCellRenderer(centralizado);
    }

    public void limparTabelaEvolucao() {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Data", "Evolução"};
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaAtendimentoProdutivida.setModel(modelo);
        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(0).setResizable(false);
        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(1).setResizable(false);
        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(2).setPreferredWidth(390);
        jTabelaAtendimentoProdutivida.getColumnModel().getColumn(2).setResizable(false);
        jTabelaAtendimentoProdutivida.getTableHeader().setReorderingAllowed(false);
        jTabelaAtendimentoProdutivida.setAutoResizeMode(jTabelaAtendimentoProdutivida.AUTO_RESIZE_OFF);
        jTabelaAtendimentoProdutivida.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        modelo.getLinhas().clear();
    }

    public void mostrarDemostrativoPSP() {
        DefaultTableModel dadosProduto = (DefaultTableModel) jTabelaAtendimentoProdutivida.getModel();
        RegistroAtendimentoInternos p = new RegistroAtendimentoInternos();
        try {
            for (RegistroAtendimentoInternos pp : control.read()) {

//                jtotalProdutosKitCompleto.setText(Integer.toString(qtdTecnicosPSP)); // Converter inteiro em string para exibir na tela 
                dadosProduto.addRow(new Object[]{formatter2.format(pp.getDataAtendimento()),pp.getNomeFunc(), pp.getNomeDepartamento(), pp.getQtdAtend(), pp.getQtdAtend() * 7, pp.getQtdAtend() * 25});
                // BARRA DE ROLAGEM HORIZONTAL
                //jTabelaAtendimentoProdutivida.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                // ALINHAR TEXTO DA TABELA CENTRALIZADO
                DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
                centralizado.setHorizontalAlignment(SwingConstants.CENTER);
                
//                DefaultTableCellRenderer corCabecalho = new DefaultTableCellRenderer();
//                corCabecalho.setBackground(new Color(0,153,204));
//                jTabelaAtendimentoProdutivida.getColumnModel().getColumn(0).setHeaderRenderer(corCabecalho);
//                jTabelaAtendimentoProdutivida.getColumnModel().getColumn(1).setHeaderRenderer(corCabecalho);
//                jTabelaAtendimentoProdutivida.getColumnModel().getColumn(2).setHeaderRenderer(corCabecalho); 
//                jTabelaAtendimentoProdutivida.getColumnModel().getColumn(3).setHeaderRenderer(corCabecalho);
//                jTabelaAtendimentoProdutivida.getColumnModel().getColumn(4).setHeaderRenderer(corCabecalho);
//                jTabelaAtendimentoProdutivida.getColumnModel().getColumn(5).setHeaderRenderer(corCabecalho);
                
                //
                jTabelaAtendimentoProdutivida.getColumnModel().getColumn(3).setCellRenderer(centralizado);
                jTabelaAtendimentoProdutivida.getColumnModel().getColumn(4).setCellRenderer(centralizado);
                jTabelaAtendimentoProdutivida.getColumnModel().getColumn(5).setCellRenderer(centralizado);
                int total = 0;
                for (int i = 0; i < dadosProduto.getRowCount(); i++) {
                    total += Integer.parseInt(dadosProduto.getValueAt(i, 3).toString());// 3rd column . row column indexes are 0 based
                    
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Produtividade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void rodaRelogio() {
        try {
            while (true) {
                Date data = new Date();
                String hora = formatter.format(data);
                String date = formatter2.format(data);
                jHoraSistemaPSP.setText(String.valueOf(hora));    // no lugar do label, por seu JTextField    
                jDataSistemaPSP.setText(String.valueOf(date));
                Thread.sleep(1000);
            }
        } catch (InterruptedException ex) {
        }
    }

//    public void SetData(Object obj, int row_index, int col_index) {
//        jTabelaAtendimentoProdutivida.getModel().setValueAt(obj, row_index, col_index);
//    }
//    public Object GetData(JTable table, int row_index, int col_index) {
//        return table.getModel().getValueAt(row_index, col_index);
// }
//    public double getSum(){
//        int rowsCount = jTabelaAtendimentoProdutivida.getRowCount();
//        double total = 0;
//        double sum = 0;
//        for(int i = 0; i < rowsCount; i++){
//          //getValueAt(i, 2) : the doubles column
//            sum = sum+(Double.parseDouble((jTabelaAtendimentoProdutivida.getValueAt(i, 2).toString())));
//        }
//        return sum += total;
//    }
//    public void somaAtendimento() {
//
//        double soma = 0;
//        double total = 0;
//        for (int i = 0; i < jTabelaAtendimentoProdutivida.getRowCount(); i++) {
//            int amount = Integer.parseInt((String) jTabelaAtendimentoProdutivida.getValueAt(i, 2));
//       soma = soma + Integer.parseInt(jTabelaAtendimentoProdutivida.getValueAt(i, 2).toString());
//
//        soma.setText(String.valueOf(total));
//        //jtextField.setText(Integer.toString(total));
//
//        try {
//            String update = "";
//            catch(Exception e2) {
//           
//                    }
//        }
//    }
}
