/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestor.Visao;

import gestor.Dao.*;
import static gestor.Visao.TelaListaPassagemInternos.DiaDom;
import static gestor.Visao.TelaListaPassagemInternos.DiaQua;
import static gestor.Visao.TelaListaPassagemInternos.DiaQui;
import static gestor.Visao.TelaListaPassagemInternos.DiaSab;
import static gestor.Visao.TelaListaPassagemInternos.DiaSeg;
import static gestor.Visao.TelaListaPassagemInternos.DiaSex;
import static gestor.Visao.TelaListaPassagemInternos.DiaTer;
import static gestor.Visao.TelaListaPassagemInternos.FotoInternoListaPassagem;
import static gestor.Visao.TelaListaPassagemInternos.jBtNovoInterno;
import static gestor.Visao.TelaListaPassagemInternos.jBtAlterarInterno;
import static gestor.Visao.TelaListaPassagemInternos.jBtExcluirInterno;
import static gestor.Visao.TelaListaPassagemInternos.jBtSalvarInterno;
import static gestor.Visao.TelaListaPassagemInternos.jBtCancelarInterno;
import static gestor.Visao.TelaListaPassagemInternos.jBtBuscarInterno;
import static gestor.Visao.TelaListaPassagemInternos.jComboBoxStatus;
import static gestor.Visao.TelaListaPassagemInternos.jDataEntrada;
import static gestor.Visao.TelaListaPassagemInternos.jIDAgenda;
import static gestor.Visao.TelaListaPassagemInternos.jIdInterno;
import static gestor.Visao.TelaListaPassagemInternos.jNomeInterno;
import static gestor.Visao.TelaListaPassagemInternos.idItem;
import static gestor.Visao.TelaListaPassagemInternos.jCheckBoxDom;
import static gestor.Visao.TelaListaPassagemInternos.jCheckBoxQua;
import static gestor.Visao.TelaListaPassagemInternos.jCheckBoxQui;
import static gestor.Visao.TelaListaPassagemInternos.jCheckBoxSab;
import static gestor.Visao.TelaListaPassagemInternos.jCheckBoxSeg;
import static gestor.Visao.TelaListaPassagemInternos.jCheckBoxSex;
import static gestor.Visao.TelaListaPassagemInternos.jCheckBoxTer;
import static gestor.Visao.TelaListaPassagemInternos.jHoraDom;
import static gestor.Visao.TelaListaPassagemInternos.jHoraDomEnt;
import static gestor.Visao.TelaListaPassagemInternos.jHoraQua;
import static gestor.Visao.TelaListaPassagemInternos.jHoraQuaEnt;
import static gestor.Visao.TelaListaPassagemInternos.jHoraQui;
import static gestor.Visao.TelaListaPassagemInternos.jHoraQuiEnt;
import static gestor.Visao.TelaListaPassagemInternos.jHoraSab;
import static gestor.Visao.TelaListaPassagemInternos.jHoraSabEnt;
import static gestor.Visao.TelaListaPassagemInternos.jHoraSeg;
import static gestor.Visao.TelaListaPassagemInternos.jHoraSegEnt;
import static gestor.Visao.TelaListaPassagemInternos.jHoraSex;
import static gestor.Visao.TelaListaPassagemInternos.jHoraSexEnt;
import static gestor.Visao.TelaListaPassagemInternos.jHoraTer;
import static gestor.Visao.TelaListaPassagemInternos.jHoraTerEnt;
import java.awt.Image;
//import static gestor.Visao.TelaListaPassagemInternos.jSituacao;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author user
 */
public class TelaBtBuscarInternoLabor extends javax.swing.JInternalFrame {

    ConexaoBancoDados conecta = new ConexaoBancoDados();
    int flag;
    String dataEntrada;
    String dataSaida;
    String situacaoEnt = "ENTRADA NA UNIDADE";
    String situacaoRet = "RETORNO A UNIDADE";
    String caminho;
    String nomeInterno;
    String idInterno;

    /**
     * Creates new form TelaPesqColaborador
     */
    public TelaBtBuscarInternoLabor() {
        initComponents();
        jPesqNomeInterno.setDocument(new LimiteDigitos(50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPesqNomeInterno = new javax.swing.JTextField();
        jBtPesqNome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaPesqInternos = new javax.swing.JTable();
        jBtEnviar = new javax.swing.JButton();
        jBtSair = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("...::: Pesquisa Internos - {TO} :::...");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listagem de Internos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 255)));

        jPesqNomeInterno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jBtPesqNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/Lupas_1338_05.gif"))); // NOI18N
        jBtPesqNome.setToolTipText("Pesquisa por Nome");
        jBtPesqNome.setContentAreaFilled(false);
        jBtPesqNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesqNomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nome:");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("Todos");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPesqNomeInterno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPesqNomeInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jBtPesqNome)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabelaPesqInternos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTabelaPesqInternos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Código", "Nome do Interno", "Situação"
            }
        ));
        jTabelaPesqInternos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaPesqInternosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaPesqInternos);
        if (jTabelaPesqInternos.getColumnModel().getColumnCount() > 0) {
            jTabelaPesqInternos.getColumnModel().getColumn(0).setMinWidth(50);
            jTabelaPesqInternos.getColumnModel().getColumn(0).setMaxWidth(50);
            jTabelaPesqInternos.getColumnModel().getColumn(1).setMinWidth(250);
            jTabelaPesqInternos.getColumnModel().getColumn(1).setMaxWidth(250);
            jTabelaPesqInternos.getColumnModel().getColumn(2).setMinWidth(150);
            jTabelaPesqInternos.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        jBtEnviar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtEnviar.setForeground(new java.awt.Color(0, 0, 255));
        jBtEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/accept.png"))); // NOI18N
        jBtEnviar.setText("Enviar");
        jBtEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEnviarActionPerformed(evt);
            }
        });

        jBtSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtSair.setForeground(new java.awt.Color(255, 0, 0));
        jBtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/Log_Out_Icon_16.png"))); // NOI18N
        jBtSair.setText("Sair");
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtEnviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtSair)
                        .addGap(0, 231, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtEnviar)
                    .addComponent(jBtSair))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pesquisas", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        setBounds(250, 20, 440, 264);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEnviarActionPerformed
        // TODO add your handling code here:
        flag = 1;
        if (flag == 1) {
            nomeInterno = "" + jTabelaPesqInternos.getValueAt(jTabelaPesqInternos.getSelectedRow(), 1);
            jPesqNomeInterno.setText(nomeInterno);
            idInterno = "" + jTabelaPesqInternos.getValueAt(jTabelaPesqInternos.getSelectedRow(), 0);
            jIdInterno.setText(idInterno);
            //
            jBtNovoInterno.setEnabled(true);
            jBtAlterarInterno.setEnabled(true);
            jBtExcluirInterno.setEnabled(true);
            jBtSalvarInterno.setEnabled(true);
            jBtCancelarInterno.setEnabled(true);
            jBtBuscarInterno.setEnabled(true);
            conecta.abrirConexao();
            try {
                conecta.executaSQL("SELECT * FROM PRONTUARIOSCRC "
                        + "INNER JOIN ITENSAGENDALABORATIVA "
                        + "ON PRONTUARIOSCRC.IdInternoCrc=ITENSAGENDALABORATIVA.IdInternoCrc "
                        + "INNER JOIN DADOSPENAISINTERNOS "
                        + "ON PRONTUARIOSCRC.IdInternoCrc=DADOSPENAISINTERNOS.IdInternoCrc "
                        + "WHERE NomeInternoCrc='" + jPesqNomeInterno.getText() + "'AND IdAgenda='" + jIDAgenda.getText() + "'");
                conecta.rs.first();
                jIdInterno.setText(conecta.rs.getString("IdInternoCrc")); //Coluna 0
                jNomeInterno.setText(conecta.rs.getString("NomeInternoCrc")); // Coluna 1  
                idItem = conecta.rs.getString("IdItem");
                jComboBoxStatus.setSelectedItem(conecta.rs.getString("StatusInterno"));
                jDataEntrada.setDate(conecta.rs.getDate("DataEntrada"));
                // Capturando foto
                caminho = conecta.rs.getString("FotoInternoCrc");
                javax.swing.ImageIcon i = new javax.swing.ImageIcon(caminho);
                FotoInternoListaPassagem.setIcon(i);
                FotoInternoListaPassagem.setIcon(new ImageIcon(i.getImage().getScaledInstance(FotoInternoListaPassagem.getWidth(), FotoInternoListaPassagem.getHeight(), Image.SCALE_DEFAULT)));
                //
                DiaSeg = conecta.rs.getInt("DiaSeg");
                if (DiaSeg == 0) {
                    jCheckBoxSeg.setSelected(true);
                } else if (DiaSeg == 1) {
                    jCheckBoxSeg.setSelected(!true);
                }
                DiaTer = conecta.rs.getInt("DiaTer");
                if (DiaTer == 0) {
                    jCheckBoxTer.setSelected(true);
                } else if (DiaTer == 1) {
                    jCheckBoxTer.setSelected(!true);
                }
                DiaQua = conecta.rs.getInt("DiaQua");
                if (DiaQua == 0) {
                    jCheckBoxQua.setSelected(true);
                } else if (DiaQua == 1) {
                    jCheckBoxQua.setSelected(!true);
                }
                DiaQui = conecta.rs.getInt("DiaQui");
                if (DiaQui == 0) {
                    jCheckBoxQui.setSelected(true);
                } else if (DiaQui == 1) {
                    jCheckBoxQui.setSelected(!true);
                }
                DiaSex = conecta.rs.getInt("DiaSex");
                if (DiaSex == 0) {
                    jCheckBoxSex.setSelected(true);
                } else if (DiaSex == 1) {
                    jCheckBoxSex.setSelected(!true);
                }
                DiaSab = conecta.rs.getInt("DiaSab");
                if (DiaSab == 0) {
                    jCheckBoxSab.setSelected(true);
                } else if (DiaSab == 1) {
                    jCheckBoxSab.setSelected(!true);
                }
                DiaDom = conecta.rs.getInt("DiaDom");
                if (DiaDom == 0) {
                    jCheckBoxDom.setSelected(true);
                } else if (DiaDom == 1) {
                    jCheckBoxDom.setSelected(!true);
                }
                // HORÁRIO DE SAÍDA
                jHoraSeg.setText(conecta.rs.getString("HoraSeg"));
                jHoraTer.setText(conecta.rs.getString("HoraTer"));
                jHoraQua.setText(conecta.rs.getString("HoraQua"));
                jHoraQui.setText(conecta.rs.getString("HoraQui"));
                jHoraSex.setText(conecta.rs.getString("HoraSex"));
                jHoraSab.setText(conecta.rs.getString("HoraSab"));
                jHoraDom.setText(conecta.rs.getString("HoraDom"));
                // HORÁRIO DE ENTRADA
                jHoraSegEnt.setText(conecta.rs.getString("HoraSegEnt"));
                jHoraTerEnt.setText(conecta.rs.getString("HoraTerEnt"));
                jHoraQuaEnt.setText(conecta.rs.getString("HoraQuaEnt"));
                jHoraQuiEnt.setText(conecta.rs.getString("HoraQuiEnt"));
                jHoraSexEnt.setText(conecta.rs.getString("HoraSexEnt"));
                jHoraSabEnt.setText(conecta.rs.getString("HoraSabEnt"));
                jHoraDomEnt.setText(conecta.rs.getString("HoraDomEnt"));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "ERRO na pesquisa por nome" + ex);
            }
             conecta.desconecta();
            dispose();
        }
    }//GEN-LAST:event_jBtEnviarActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtSairActionPerformed

    private void jBtPesqNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesqNomeActionPerformed
        // TODO add your handling code here:              
        flag = 1;
        if (jPesqNomeInterno.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe um nome ou parte do nome para pesquisar.");
            jPesqNomeInterno.requestFocus();
        } else {            
            buscarInternos("SELECT * FROM PRONTUARIOSCRC "
                    + "INNER JOIN ITENSAGENDALABORATIVA "
                    + "ON PRONTUARIOSCRC.IdInternoCrc=ITENSAGENDALABORATIVA.IdInternoCrc "
                    + "WHERE NomeInternoCrc LIKE'" + jPesqNomeInterno.getText() + "%' AND IdAgenda='" + jIDAgenda.getText() + "'");
        }
    }//GEN-LAST:event_jBtPesqNomeActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        flag = 1;
        if (evt.getStateChange() == evt.SELECTED) {            
            this.buscarInternos("SELECT * FROM PRONTUARIOSCRC "
                    + "INNER JOIN ITENSAGENDALABORATIVA "
                    + "ON PRONTUARIOSCRC.IdInternoCrc=ITENSAGENDALABORATIVA.IdInternoCrc "
                    + "WHERE IdAgenda='" + jIDAgenda.getText() + "'");
        } else {
            limparTabelaInternos();
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jTabelaPesqInternosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaPesqInternosMouseClicked
        // TODO add your handling code here:
        if (flag == 1) {
            nomeInterno = "" + jTabelaPesqInternos.getValueAt(jTabelaPesqInternos.getSelectedRow(), 1);
            jPesqNomeInterno.setText(nomeInterno);
            idInterno = "" + jTabelaPesqInternos.getValueAt(jTabelaPesqInternos.getSelectedRow(), 0);
            jIdInterno.setText(idInterno);
        }
    }//GEN-LAST:event_jTabelaPesqInternosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtEnviar;
    private javax.swing.JButton jBtPesqNome;
    private javax.swing.JButton jBtSair;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPesqNomeInterno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTabelaPesqInternos;
    // End of variables declaration//GEN-END:variables

//Preencher tabela com todos os VISITANTES
    public void buscarInternos(String sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Nome do Interno ", "Situação"};
        conecta.abrirConexao();
        try {
            conecta.executaSQL(sql);
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("IdInternoCrc"), conecta.rs.getString("NomeInternoCrc"), conecta.rs.getString("SituacaoCrc")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não existem dados a serem EXIBIDOS !!!");
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaPesqInternos.setModel(modelo);
        jTabelaPesqInternos.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTabelaPesqInternos.getColumnModel().getColumn(0).setResizable(false);
        jTabelaPesqInternos.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTabelaPesqInternos.getColumnModel().getColumn(1).setResizable(false);
        jTabelaPesqInternos.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTabelaPesqInternos.getColumnModel().getColumn(2).setResizable(false);
        jTabelaPesqInternos.getTableHeader().setReorderingAllowed(false);
        jTabelaPesqInternos.setAutoResizeMode(jTabelaPesqInternos.AUTO_RESIZE_OFF);
        jTabelaPesqInternos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        alinharCamposTabela();
        conecta.desconecta();
    }

    public void limparTabelaInternos() {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Nome do Interno ", "Situação"};
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaPesqInternos.setModel(modelo);
        jTabelaPesqInternos.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTabelaPesqInternos.getColumnModel().getColumn(0).setResizable(false);
        jTabelaPesqInternos.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTabelaPesqInternos.getColumnModel().getColumn(1).setResizable(false);
        jTabelaPesqInternos.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTabelaPesqInternos.getColumnModel().getColumn(2).setResizable(false);
        jTabelaPesqInternos.getTableHeader().setReorderingAllowed(false);
        jTabelaPesqInternos.setAutoResizeMode(jTabelaPesqInternos.AUTO_RESIZE_OFF);
        jTabelaPesqInternos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        modelo.getLinhas().clear();
    }

    public void alinharCamposTabela() {
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        //
        jTabelaPesqInternos.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jTabelaPesqInternos.getColumnModel().getColumn(2).setCellRenderer(centralizado);
    }
}
