/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestor.Visao;

import gestor.Controle.ControleItensPrevisaoSaida;
import gestor.Controle.ControleItensSaidaInterno;
import gestor.Controle.ControleItensSaidaInternoPortaria;
import gestor.Controle.ControleMovInternos;
import gestor.Dao.ConexaoBancoDados;
import gestor.Modelo.ItensPrevisaoSaida;
import gestor.Modelo.ItensSaidaInterno;
import gestor.Modelo.PrevisaoSaida;
import static gestor.Visao.TelaBuscarPrevisaoSaidaInternos.jDataPrevRetorno;
import static gestor.Visao.TelaBuscarPrevisaoSaidaInternos.jDataSaida;
import static gestor.Visao.TelaBuscarPrevisaoSaidaInternos.jDescricaoOp;
import static gestor.Visao.TelaBuscarPrevisaoSaidaInternos.jDestinoInterno;
import static gestor.Visao.TelaBuscarPrevisaoSaidaInternos.jDocumento;
import static gestor.Visao.TelaBuscarPrevisaoSaidaInternos.jIdLanc;
import static gestor.Visao.TelaBuscarPrevisaoSaidaInternos.jTabelaSaidaInternos;
import static gestor.Visao.TelaLoginSenha.nameUser;
import static gestor.Visao.TelaModuloPrincipal.jDataSistema;
import static gestor.Visao.TelaModuloPrincipal.jHoraSistema;
import static gestor.Visao.TelaSaidaInterno.jTabelaItensInterno;
import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronaldo
 */
public class TelaProgressoPrevisao extends javax.swing.JInternalFrame {

    ConexaoBancoDados conecta = new ConexaoBancoDados();
    PrevisaoSaida objPrevSaida = new PrevisaoSaida();
    ItensPrevisaoSaida objItensPreSaida = new ItensPrevisaoSaida();
    ItensSaidaInterno objItemSaida = new ItensSaidaInterno();
    ControleItensSaidaInterno control = new ControleItensSaidaInterno();
    ControleItensPrevisaoSaida controle = new ControleItensPrevisaoSaida();
    ControleItensSaidaInternoPortaria controlePort = new ControleItensSaidaInternoPortaria(); // Grava os registros na tabela de ITENSCRCPORTARIA   
    ControleMovInternos controlMov = new ControleMovInternos();  // HISTÓRICO DE MOVIMENTAÇÃO DE SAIDA NO CRC
    //         
    String confirmaSaida = "Não"; // CRC informa como não para portaria poder visualizar a saida
    String utilizacaoSaida = "Não";
    String evadidos = "";
    String dataInicial, dataFinal, dataSaida;
    String beneficio = "SAIDA TEMPORARIA";
    int segundos = 0;

    /**
     * Creates new form TelaFechamentoCrc
     */
    public TelaProgressoPrevisao() {
        initComponents();        
        barraProgresso obj = new barraProgresso();
        obj.start();        
        obj.stop();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblCarregando = new javax.swing.JLabel();

        setClosable(true);
        setTitle("...:::  Transferencia Previsão :::...");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Aguarde a importação dos itens...");

        jProgressBar1.setForeground(new java.awt.Color(204, 51, 0));
        jProgressBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jProgressBar1.setStringPainted(true);

        lblCarregando.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCarregando.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setBounds(450, 100, 455, 142);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblCarregando;
    // End of variables declaration//GEN-END:variables

    public class barraProgresso extends Thread {

        public void run() {
            for (int i = 0; i < 101; i++) {
                try {
                    Thread.sleep(100);
                    jProgressBar1.setValue(i);
                  
                } catch (Exception e) {
                }
            }
        }
    }   
}
