/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestor.Visao;

import gestor.Dao.ConexaoBancoDados;
import static gestor.Visao.TelaAcessosPortariaInterna.caminhoFotoAdvogado;
import static gestor.Visao.TelaAcessosPortariaInterna.caminhoFotoColaborador;
import static gestor.Visao.TelaAcessosPortariaInterna.caminhoFotoVisita;
import static gestor.Visao.TelaAcessosPortariaInterna.jIdTransiente;
import static gestor.Visao.TelaAcessosPortariaInterna.tipoVisita;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author ronaldo
 */
public class TelaFotoVisitasPortariaInterna extends javax.swing.JDialog {

    ConexaoBancoDados conecta = new ConexaoBancoDados();

    public static TelaAcessosPortariaInterna telaAcessoTransientes;

    /**
     * Creates new form TelaFotoCrc
     * @param parent
     * @param modal
     */
    public TelaFotoVisitasPortariaInterna(TelaAcessosPortariaInterna parent, boolean modal) {
        this.telaAcessoTransientes = parent;
        this.setModal(modal);
        setLocationRelativeTo(telaAcessoTransientes);
        initComponents();       
        if (tipoVisita == 0) {
            buscarFotoAdvogado();
        } else if (tipoVisita == 1) {
            buscarFotoColaborador();
        } else if (tipoVisita == 2) {
            buscarFotoVisitas();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFotoVisitanteTranseinte = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("...::: Foto Visitante/Colaborador/Advogado :::...");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFotoVisitanteTranseinte, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFotoVisitanteTranseinte, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFotoVisitasPortariaInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFotoVisitasPortariaInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFotoVisitasPortariaInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFotoVisitasPortariaInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaFotoVisitasPortariaInterna dialog = new TelaFotoVisitasPortariaInterna(telaAcessoTransientes, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jFotoVisitanteTranseinte;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void buscarFotoAdvogado() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM ADVOGADOS WHERE IdAdvogado='" + jIdTransiente.getText() + "'");
            conecta.rs.first();
            caminhoFotoAdvogado = conecta.rs.getString("FotoAdvogado");
            // Capturando foto                
            javax.swing.ImageIcon a = new javax.swing.ImageIcon(caminhoFotoAdvogado);
            jFotoVisitanteTranseinte.setIcon(a);
            jFotoVisitanteTranseinte.setIcon(new ImageIcon(a.getImage().getScaledInstance(jFotoVisitanteTranseinte.getWidth(), jFotoVisitanteTranseinte.getHeight(), Image.SCALE_DEFAULT)));
            //
        } catch (Exception e) {
        }
        conecta.desconecta();
    }

    public void buscarFotoVisitas() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM VISITASDIVERSAS WHERE IdVisita='" + jIdTransiente.getText() + "'");
            conecta.rs.first();
            caminhoFotoVisita = conecta.rs.getString("FotoVisita");
            // Capturando foto                
            javax.swing.ImageIcon b = new javax.swing.ImageIcon(caminhoFotoVisita);
            jFotoVisitanteTranseinte.setIcon(b);
            jFotoVisitanteTranseinte.setIcon(new ImageIcon(b.getImage().getScaledInstance(jFotoVisitanteTranseinte.getWidth(), jFotoVisitanteTranseinte.getHeight(), Image.SCALE_DEFAULT)));
            //
        } catch (Exception e) {
        }
        conecta.desconecta();
    }

    public void buscarFotoColaborador() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM COLABORADOR WHERE IdFunc='" + jIdTransiente.getText() + "'");
            conecta.rs.first();
            caminhoFotoColaborador = conecta.rs.getString("ImagemFunc");
            // Capturando foto                
            javax.swing.ImageIcon c = new javax.swing.ImageIcon(caminhoFotoColaborador);
            jFotoVisitanteTranseinte.setIcon(c);
            jFotoVisitanteTranseinte.setIcon(new ImageIcon(c.getImage().getScaledInstance(jFotoVisitanteTranseinte.getWidth(), jFotoVisitanteTranseinte.getHeight(), Image.SCALE_DEFAULT)));            
        } catch (Exception e) {
        }
        conecta.desconecta();
    }
}
