/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestor.Visao;

import gestor.Controle.ControleItensSolicitacaoMateriaisADM;
import gestor.Controle.ControleLogSistema;
import gestor.Controle.ControleSolicitacaoComprasADM;
import gestor.Dao.ConexaoBancoDados;
import Utilitarios.ModeloTabela;
import gestor.Modelo.AprovarSolicitacaoCompras;
import gestor.Modelo.ItensSolicitacaoCompras;
import gestor.Modelo.LogSistema;
import gestor.Modelo.SolicitacaoComprasAC;
import static gestor.Visao.TelaAprovarSolicitacaoCompras.acaoAlt;
import static gestor.Visao.TelaAprovarSolicitacaoCompras.idProduto;
import static gestor.Visao.TelaAprovarSolicitacaoCompras.jIdAprova;
import static gestor.Visao.TelaAprovarSolicitacaoCompras.jIdSolicitacao;
import static gestor.Visao.TelaAprovarSolicitacaoCompras.jDataAprova;
import static gestor.Visao.TelaAprovarSolicitacaoCompras.jStatusAprova;
import static gestor.Visao.TelaAprovarSolicitacaoCompras.jTabelaItensAprovado;
import static gestor.Visao.TelaAprovarSolicitacaoCompras.jValorTotalAprovado;
import static gestor.Visao.TelaAprovarSolicitacaoCompras.linhaSelecionada;
import static gestor.Visao.TelaAprovarSolicitacaoCompras.valorAprovado;
import static gestor.Visao.TelaAprovarSolicitacaoCompras.valorSolicitado;
import static gestor.Visao.TelaLoginSenha.nameUser;
import static gestor.Visao.TelaModuloPrincipal.jDataSistema;
import static gestor.Visao.TelaModuloPrincipal.jHoraSistema;
import java.awt.Color;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Currency;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Ronaldo
 */
public class TelaItensSolicitacaoCompras extends javax.swing.JDialog {

    ConexaoBancoDados conecta = new ConexaoBancoDados();
    AprovarSolicitacaoCompras objAprovaSol = new AprovarSolicitacaoCompras();
    ItensSolicitacaoCompras objItensCompra = new ItensSolicitacaoCompras();
    // ATUALIZAR ITENS DA SOLICITAÇÃO DE COMPRAS
    ControleItensSolicitacaoMateriaisADM controle = new ControleItensSolicitacaoMateriaisADM();
    // ATUALIZAR TABELA DE SOLICITAÇÃO DE COMPRAS
    SolicitacaoComprasAC objSoliMat = new SolicitacaoComprasAC();
    ControleSolicitacaoComprasADM controlSol = new ControleSolicitacaoComprasADM();
    //
    ControleLogSistema controlLog = new ControleLogSistema();
    LogSistema objLogSys = new LogSistema();
    // Variáveis para gravar o log
    String nomeModuloTela3 = "Administração:Aprovação de Solicitação Compras:Ap. Individual";
    //
    int acao;
    String statusMov;
    String horaMov;
    String dataModFinal;
    double valorUnitario = 0;
    double qtdItem = 0;
    String qtdItemTab;
    double valorTotalItem2 = 0;
    float valorTotalItem = 0;
    double valorUnitario1 = 0;
    String valorUnitario2;
    double valorTotalSoli = 0;
    String valorTotalSoli1;
    String valorTotalSoli2;
    //
    String statusAprovacao = "Aprovado Parcial";
    String aprovaSolicitacao = "Sim";
    String situacaoSoliticacao = "Liberada";
    //
    String codigoProduto, codigoAprova;
    int navega = 0;
    float valorSolicitacao = 0;

    /**
     * Creates new form TelaItensSolicitacaoCompras
     */
    public static TelaAprovarSolicitacaoCompras aprovarSolicitacao;

    public TelaItensSolicitacaoCompras(TelaAprovarSolicitacaoCompras parent, boolean modal) {
        this.aprovarSolicitacao = parent;
        this.setModal(modal);
        setLocationRelativeTo(aprovarSolicitacao);
        initComponents();
        corCampos();
        popularCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBtSalvarAprovacao = new javax.swing.JButton();
        jBtAlterarAprovacao = new javax.swing.JButton();
        jBtSairAprovacao = new javax.swing.JButton();
        jBtExcluirAprovacao = new javax.swing.JButton();
        jBtCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBtPrimeiroRegistro = new javax.swing.JButton();
        jBtProximoRegistro = new javax.swing.JButton();
        jBtAnteriorRegistro = new javax.swing.JButton();
        jBtUltimoRegistro = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCodigoProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDescricaoProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jUnidadeProduto = new javax.swing.JTextField();
        jQuantidadeSolicitada = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jValorSolicitado = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxStatusAprovacao = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jValorSolicitadoTotal = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("...::: Itens da Solicitação de Compras :::...");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBtSalvarAprovacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/Botoes_5117_floppy_disk_48.png"))); // NOI18N
        jBtSalvarAprovacao.setToolTipText("Gravar");
        jBtSalvarAprovacao.setEnabled(false);
        jBtSalvarAprovacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalvarAprovacaoActionPerformed(evt);
            }
        });

        jBtAlterarAprovacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/refresh-reload-icone-6258-48.png"))); // NOI18N
        jBtAlterarAprovacao.setToolTipText("Alterar");
        jBtAlterarAprovacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarAprovacaoActionPerformed(evt);
            }
        });

        jBtSairAprovacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/shutdown-icone-6920-48.png"))); // NOI18N
        jBtSairAprovacao.setToolTipText("Sair");
        jBtSairAprovacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairAprovacaoActionPerformed(evt);
            }
        });

        jBtExcluirAprovacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/trash-bin-icone-7877-48.png"))); // NOI18N
        jBtExcluirAprovacao.setToolTipText("Excluir");
        jBtExcluirAprovacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirAprovacaoActionPerformed(evt);
            }
        });

        jBtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/to-cancel-an-error-gtk-icone-4406-48.png"))); // NOI18N
        jBtCancelar.setToolTipText("Cancelar");
        jBtCancelar.setEnabled(false);
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jBtSalvarAprovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtAlterarAprovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtExcluirAprovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtSairAprovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtAlterarAprovacao, jBtCancelar, jBtExcluirAprovacao, jBtSairAprovacao, jBtSalvarAprovacao});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtSalvarAprovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jBtSairAprovacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtAlterarAprovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jBtExcluirAprovacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtAlterarAprovacao, jBtCancelar, jBtExcluirAprovacao, jBtSairAprovacao, jBtSalvarAprovacao});

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBtPrimeiroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/7857_16x16.png"))); // NOI18N
        jBtPrimeiroRegistro.setToolTipText("Primeiro");
        jBtPrimeiroRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPrimeiroRegistroActionPerformed(evt);
            }
        });

        jBtProximoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/7854_16x16.png"))); // NOI18N
        jBtProximoRegistro.setToolTipText("Próximo");
        jBtProximoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtProximoRegistroActionPerformed(evt);
            }
        });

        jBtAnteriorRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/7856_16x16.png"))); // NOI18N
        jBtAnteriorRegistro.setToolTipText("Anterior");
        jBtAnteriorRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAnteriorRegistroActionPerformed(evt);
            }
        });

        jBtUltimoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/7855_16x16.png"))); // NOI18N
        jBtUltimoRegistro.setToolTipText("Último");
        jBtUltimoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtUltimoRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jBtPrimeiroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtAnteriorRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jBtProximoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtUltimoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtAnteriorRegistro, jBtPrimeiroRegistro, jBtProximoRegistro, jBtUltimoRegistro});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jBtPrimeiroRegistro)
                .addComponent(jBtProximoRegistro)
                .addComponent(jBtAnteriorRegistro)
                .addComponent(jBtUltimoRegistro))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtAnteriorRegistro, jBtPrimeiroRegistro, jBtProximoRegistro, jBtUltimoRegistro});

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Código");

        jCodigoProduto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCodigoProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jCodigoProduto.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Descrição do Produto");

        jDescricaoProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDescricaoProduto.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Unid.");

        jUnidadeProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jUnidadeProduto.setEnabled(false);

        jQuantidadeSolicitada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jQuantidadeSolicitada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jQuantidadeSolicitada.setEnabled(false);
        jQuantidadeSolicitada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jQuantidadeSolicitadaFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Quant.");

        jValorSolicitado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jValorSolicitado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jValorSolicitado.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Valor R$");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Status");

        jComboBoxStatusAprovacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxStatusAprovacao.setForeground(new java.awt.Color(153, 0, 102));
        jComboBoxStatusAprovacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aprovado", "Aprovado Parcialmente", "Não Aprovado" }));
        jComboBoxStatusAprovacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBoxStatusAprovacao.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Valor Total");

        jValorSolicitadoTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jValorSolicitadoTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jValorSolicitadoTotal.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxStatusAprovacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jUnidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jQuantidadeSolicitada, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jValorSolicitado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jValorSolicitadoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDescricaoProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxStatusAprovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jUnidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jQuantidadeSolicitada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jValorSolicitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jValorSolicitadoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtSalvarAprovacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalvarAprovacaoActionPerformed
        // TODO add your handling code here:
        statusAprovacao = "Aprovado Total";
        verificarProdutoAprovado();
        DecimalFormat qtdReal = new DecimalFormat("#,##00.0");
        qtdReal.setCurrency(Currency.getInstance(new Locale("pt", "BR")));
        if (jQuantidadeSolicitada.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe a quantidade a ser aprovada.");
        } else {
            objItensCompra.setUsuarioInsert(nameUser);
            objItensCompra.setDataInsert(dataModFinal);
            objItensCompra.setHorarioInsert(horaMov);
            try {
                objItensCompra.setQtdItem(qtdReal.parse(jQuantidadeSolicitada.getText()).floatValue());
                objItensCompra.setValorUnitarioItem(qtdReal.parse(jValorSolicitado.getText()).floatValue());
                objItensCompra.setValorTotalItem(qtdReal.parse(jValorSolicitadoTotal.getText()).floatValue());
            } catch (ParseException ex) {
            }
            objItensCompra.setIdAprova(Integer.valueOf(jIdAprova.getText()));
            objItensCompra.setDataAprova(jDataAprova.getDate());
            objItensCompra.setIdProd(Integer.valueOf(jCodigoProduto.getText()));
            objItensCompra.setNomeProduto(jDescricaoProduto.getText());
            // INCLUIR O(S) ITEN(S) NA TABELA ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM
            if (acao == 1) {
                if (jCodigoProduto.getText().equals(codigoProduto) && jIdAprova.getText().equals(codigoAprova)) {
                    JOptionPane.showMessageDialog(rootPane, "Produto já cadastrado.");
                    Atualizar();
                } else {
                    // GRAVAR OS PRODUTOS NA  TABELA ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM
                    controle.incluirItensAprovadoADM(objItensCompra);
                    objItensCompra.setUsuarioUp(nameUser);
                    objItensCompra.setDataUp(dataModFinal);
                    objItensCompra.setHorarioUp(horaMov);
                    // ATUALIZAR OS CAMPOS DA SOLICITAÇÃO QUANDO APROVADA (AprovaSol,StatusAprovacao)
                    objItensCompra.setIdSol(Integer.valueOf(jIdSolicitacao.getText()));
                    objItensCompra.setStatusAprovacao(statusAprovacao); // Status APROVADO
                    objItensCompra.setAprovaSolicitacao(aprovaSolicitacao); // Aprovacao = "Sim"
                    controle.atualizaCampoAprovaSolicitacaoMaterialADM(objItensCompra);
                    objLog3();
                    controlLog.incluirLogSistema(objLogSys); // Grava o log da operação    
                    preencherTabelaItensAprovado("SELECT * FROM ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM "
                            + "INNER JOIN APROVACAO_SOLICITACAO_COMPRAS_ADM "
                            + "ON ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdAprova=APROVACAO_SOLICITACAO_COMPRAS_ADM.IdAprova "
                            + "INNER JOIN PRODUTOS_AC "
                            + "ON ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdProd=PRODUTOS_AC.IdProd "
                            + "WHERE ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdAprova='" + jIdAprova.getText() + "'");
                    JOptionPane.showMessageDialog(rootPane, "Registro gravado com sucesso.");
                    bloquearCampos();
                    Atualizar();
                }
            }
            if (acao == 2) {
                objItensCompra.setUsuarioUp(nameUser);
                objItensCompra.setDataUp(dataModFinal);
                objItensCompra.setHorarioUp(horaMov);
                //
                objItensCompra.setIdAprova(Integer.valueOf(jIdAprova.getText()));
                objItensCompra.setIdProd(Integer.valueOf(jCodigoProduto.getText()));
                controle.alterarItensAprovadoADM(objItensCompra);
                // ATUALIZAR OS CAMPOS DA SOLICITAÇÃO QUANDO APROVADA (AprovaSol,StatusAprovacao)
                objItensCompra.setIdSol(Integer.valueOf(jIdSolicitacao.getText()));
                objItensCompra.setStatusAprovacao(statusAprovacao); // Status APROVADO
                objItensCompra.setAprovaSolicitacao(aprovaSolicitacao); // Aprovacao = "Sim"
                controle.atualizaCampoAprovaSolicitacaoMaterialADM(objItensCompra);
                objLog3();
                controlLog.incluirLogSistema(objLogSys); // Grava o log da operação    
                preencherTabelaItensAprovado("SELECT * FROM ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM "
                        + "INNER JOIN APROVACAO_SOLICITACAO_COMPRAS_ADM "
                        + "ON ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdAprova=APROVACAO_SOLICITACAO_COMPRAS_ADM.IdAprova "
                        + "INNER JOIN PRODUTOS_AC "
                        + "ON ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdProd=PRODUTOS_AC.IdProd "
                        + "WHERE ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdAprova='" + jIdAprova.getText() + "'");
                JOptionPane.showMessageDialog(rootPane, "Registro gravado com sucesso.");
                bloquearCampos();
                Atualizar();
            }
        }
    }//GEN-LAST:event_jBtSalvarAprovacaoActionPerformed

    private void jBtAlterarAprovacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarAprovacaoActionPerformed
        // TODO add your handling code here:
        objAprovaSol.setStatusAprova(jStatusAprova.getText());
        if (jStatusAprova.getText().equals("FINALIZADO")) {
            JOptionPane.showMessageDialog(rootPane, "Esse registro não poderá ser modificado, o mesmo encontra-se FINALIZADO");
        } else {
            acao = 2;
            Alterar();
        }
    }//GEN-LAST:event_jBtAlterarAprovacaoActionPerformed

    private void jBtExcluirAprovacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirAprovacaoActionPerformed
        // TODO add your handling code here:
        DecimalFormat qtdReal = new DecimalFormat("#,##00.0");
        qtdReal.setCurrency(Currency.getInstance(new Locale("pt", "BR")));
        objAprovaSol.setStatusAprova(jStatusAprova.getText());
        if (jStatusAprova.getText().equals("FINALIZADO")) {
            JOptionPane.showMessageDialog(rootPane, "Esse registro não poderá ser excluído, o mesmo encontra-se FINALIZADO");
        } else {
            statusMov = "Excluiu";
            horaMov = jHoraSistema.getText();
            dataModFinal = jDataSistema.getText();
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o registro selecionado?", "Confirmação",
                    JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                // CALCULAR VALOR A SER DEDUZIDO DA APROVAÇÃO DE COMPRAS
                try {
                    objItensCompra.setValorTotalItem(qtdReal.parse(jValorSolicitadoTotal.getText()).floatValue());
                } catch (ParseException ex) {
                }
                valorSolicitacao = (float) (valorAprovado - objItensCompra.getValorTotalItem());
                objSoliMat.setValorAprovado(valorSolicitacao);
                objSoliMat.setSituacao(statusAprovacao);
                objSoliMat.setIdSol(Integer.valueOf(jIdSolicitacao.getText()));
                controlSol.alterarCampoSolicitacaoMaterialADM(objSoliMat); // ATUALIZAR NA TABELA SOLICITACAO_PRODUTOS_ADM
                // EXCLUIR PRODUTO NA TABELA ITENS_APROVACAO_PRODUTOS_ADM
                objItensCompra.setIdAprova(Integer.valueOf(jIdAprova.getText()));
                objItensCompra.setIdProd(Integer.valueOf(jCodigoProduto.getText()));
                controle.excluirItensAprovadoADM(objItensCompra);
                //
                objLog3();
                controlLog.incluirLogSistema(objLogSys); // Grava o log da operação                                                  
                DecimalFormat vu = new DecimalFormat("#,##0.00");
                String vlSolicitado = vu.format(valorSolicitacao);
                jValorTotalAprovado.setText(vlSolicitado);
                //
                preencherTabelaItensAprovado("SELECT * FROM ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM "
                        + "INNER JOIN APROVACAO_SOLICITACAO_COMPRAS_ADM "
                        + "ON ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdAprova=APROVACAO_SOLICITACAO_COMPRAS_ADM.IdAprova "
                        + "INNER JOIN PRODUTOS_AC "
                        + "ON ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdProd=PRODUTOS_AC.IdProd "
                        + "WHERE ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdAprova='" + jIdAprova.getText() + "'");
                JOptionPane.showMessageDialog(rootPane, "Registro gravado com sucesso.");
                Atualizar();
            }
        }
    }//GEN-LAST:event_jBtExcluirAprovacaoActionPerformed

    private void jBtSairAprovacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairAprovacaoActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtSairAprovacaoActionPerformed

    private void jBtPrimeiroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPrimeiroRegistroActionPerformed
        // TODO add your handling code here:
        try {
            conecta.rs.first();
            mostrarDados();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não exisem mais dados a serem EXIBIDOS.");
        }
    }//GEN-LAST:event_jBtPrimeiroRegistroActionPerformed

    private void jBtProximoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtProximoRegistroActionPerformed
        // TODO add your handling code here:
        try {
            conecta.rs.next();
            mostrarDados();
            navega = 2;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jBtProximoRegistroActionPerformed

    private void jBtAnteriorRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAnteriorRegistroActionPerformed
        // TODO add your handling code here:
        try {
            conecta.rs.previous();
            mostrarDados();
            navega = 1;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não exisem mais dados a serem EXIBIDOS.");
        }
    }//GEN-LAST:event_jBtAnteriorRegistroActionPerformed

    private void jBtUltimoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtUltimoRegistroActionPerformed
        // TODO add your handling code here:
        try {
            conecta.rs.last();
            mostrarDados();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não exisem mais dados a serem EXIBIDOS.");
        }
    }//GEN-LAST:event_jBtUltimoRegistroActionPerformed

    private void jQuantidadeSolicitadaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jQuantidadeSolicitadaFocusLost
        // TODO add your handling code here:
        DecimalFormat qtdReal = new DecimalFormat("#,##00.0");
        qtdReal.setCurrency(Currency.getInstance(new Locale("pt", "BR")));
        try {
            objItensCompra.setQtdItem(qtdReal.parse(jQuantidadeSolicitada.getText()).floatValue());
            objItensCompra.setValorUnitarioItem(qtdReal.parse(jValorSolicitado.getText()).floatValue());
            objItensCompra.setValorTotalItem(qtdReal.parse(jValorSolicitadoTotal.getText()).floatValue());
        } catch (ParseException ex) {
        }
        valorTotalItem = objItensCompra.getQtdItem() * objItensCompra.getValorUnitarioItem();
        objItensCompra.setValorTotalItem(valorTotalItem);
        DecimalFormat vti = new DecimalFormat("#,##0.00");
        String vlTotalItem = vti.format(valorTotalItem);
        jValorSolicitadoTotal.setText(vlTotalItem);
    }//GEN-LAST:event_jQuantidadeSolicitadaFocusLost

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        // TODO add your handling code here:
        Cancelar();
    }//GEN-LAST:event_jBtCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaItensSolicitacaoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaItensSolicitacaoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaItensSolicitacaoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaItensSolicitacaoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaItensSolicitacaoCompras dialog = new TelaItensSolicitacaoCompras(aprovarSolicitacao, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAlterarAprovacao;
    private javax.swing.JButton jBtAnteriorRegistro;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtExcluirAprovacao;
    private javax.swing.JButton jBtPrimeiroRegistro;
    private javax.swing.JButton jBtProximoRegistro;
    private javax.swing.JButton jBtSairAprovacao;
    private javax.swing.JButton jBtSalvarAprovacao;
    private javax.swing.JButton jBtUltimoRegistro;
    public static javax.swing.JTextField jCodigoProduto;
    private javax.swing.JComboBox jComboBoxStatusAprovacao;
    public static javax.swing.JTextField jDescricaoProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JFormattedTextField jQuantidadeSolicitada;
    public static javax.swing.JTextField jUnidadeProduto;
    public static javax.swing.JFormattedTextField jValorSolicitado;
    public static javax.swing.JFormattedTextField jValorSolicitadoTotal;
    // End of variables declaration//GEN-END:variables

    public void corCampos() {
        jCodigoProduto.setBackground(Color.white);
        jComboBoxStatusAprovacao.setBackground(Color.white);
        jDescricaoProduto.setBackground(Color.white);
        jUnidadeProduto.setBackground(Color.white);
        jQuantidadeSolicitada.setBackground(Color.white);
        jValorSolicitado.setBackground(Color.white);
        jValorSolicitadoTotal.setBackground(Color.white);
    }

    public void mostrarDados() {
        try {
            jCodigoProduto.setText(conecta.rs.getString("IdProd"));
            jDescricaoProduto.setText(conecta.rs.getString("DescricaoProd"));
            jUnidadeProduto.setText(conecta.rs.getString("UnidadeProd"));
            //
            qtdItem = conecta.rs.getFloat("QtdAprova");
            DecimalFormat vi = new DecimalFormat("#,##0.00");
            String vqtdItem = vi.format(qtdItem);
            jQuantidadeSolicitada.setText(vqtdItem);
            // Formata o valor para ser exibido na tela no formato BR
            valorUnitario = conecta.rs.getFloat("ValorUnitario");
            DecimalFormat vu = new DecimalFormat("#,##0.00");
            String vlUnitario = vu.format(valorUnitario);
            jValorSolicitado.setText(vlUnitario);
            //
            valorTotalItem2 = conecta.rs.getFloat("ValorTotal");
            DecimalFormat vti = new DecimalFormat("#,##0.00");
            String vlTotalItem = vti.format(valorTotalItem2);
            jValorSolicitadoTotal.setText(vlTotalItem);
        } catch (Exception e) {
            if (navega == 1) {
                JOptionPane.showMessageDialog(null, "Você já está no primeiro registro.");
            } else if (navega == 2) {
                JOptionPane.showMessageDialog(null, "Você já está no último registro.");
            } else {
                JOptionPane.showMessageDialog(null, "Não exisem mais dados a serem EXIBIDOS.");
                navega = 0;
            }
        }
    }

    public void popularCampos() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM "
                    + "INNER JOIN PRODUTOS_AC "
                    + "ON ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdProd=PRODUTOS_AC.IdProd "
                    + "WHERE ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdAprova='" + jIdAprova.getText() + "'");
            conecta.rs.first();
            jCodigoProduto.setText(conecta.rs.getString("IdProd"));
            jDescricaoProduto.setText(conecta.rs.getString("DescricaoProd"));
            jUnidadeProduto.setText(conecta.rs.getString("UnidadeProd"));
            //
            qtdItem = conecta.rs.getFloat("QtdAprova");
            DecimalFormat vi = new DecimalFormat("#,##0.00");
            String vqtdItem = vi.format(qtdItem);
            jQuantidadeSolicitada.setText(vqtdItem);
            // Formata o valor para ser exibido na tela no formato BR
            valorUnitario = conecta.rs.getFloat("ValorUnitario");
            DecimalFormat vu = new DecimalFormat("#,##0.00");
            String vlUnitario = vu.format(valorUnitario);
            jValorSolicitado.setText(vlUnitario);
            //
            valorTotalItem2 = conecta.rs.getFloat("ValorTotal");
            DecimalFormat vti = new DecimalFormat("#,##0.00");
            String vlTotalItem = vti.format(valorTotalItem2);
            jValorSolicitadoTotal.setText(vlTotalItem);
        } catch (Exception e) {
        }
    }

    public void Alterar() {
        jBtAlterarAprovacao.setEnabled(!true);
        jBtSalvarAprovacao.setEnabled(true);
        jBtExcluirAprovacao.setEnabled(!true);
        jBtCancelar.setEnabled(true);
        //
        jComboBoxStatusAprovacao.setEnabled(true);
        jQuantidadeSolicitada.setEnabled(true);
    }

    public void bloquearCampos() {
        jBtSalvarAprovacao.setEnabled(true);
        jBtExcluirAprovacao.setEnabled(true);
        jComboBoxStatusAprovacao.setEnabled(!true);
        jQuantidadeSolicitada.setEnabled(!true);
    }

    public void Cancelar() {
        jBtAlterarAprovacao.setEnabled(true);
        jBtSalvarAprovacao.setEnabled(true);
        jBtExcluirAprovacao.setEnabled(true);
        jComboBoxStatusAprovacao.setEnabled(!true);
        jQuantidadeSolicitada.setEnabled(!true);
        jBtCancelar.setEnabled(!true);
    }

    public void verificarProdutoAprovado() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM WHERE IdProd='" + jCodigoProduto.getText() + "'AND IdAprova='" + jIdAprova.getText() + "'");
            conecta.rs.first();
            codigoProduto = conecta.rs.getString("IdProd");
            codigoAprova = conecta.rs.getString("IdAprova");
        } catch (Exception e) {
        }
        conecta.desconecta();
    }

    public void Atualizar() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM "
                    + "INNER JOIN PRODUTOS_AC "
                    + "ON ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdProd=PRODUTOS_AC.IdProd "
                    + "WHERE ITENS_APROVACAO_SOLICITACAO_COMPRAS_ADM.IdAprova='" + jIdAprova.getText() + "'");
            conecta.rs.next();
            mostrarDados();
        } catch (Exception e) {
        }
    }

    public void preencherTabelaItensAprovado(String sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Descrição Produto", "UN", "Qtd.", "Vl. Item", "Vl. Total"};
        conecta.abrirConexao();
        try {
            conecta.executaSQL(sql);
            conecta.rs.first();
            //          count = 0;
            do {
                //          count = count + 1;
                qtdItem = conecta.rs.getFloat("QtdAprova");
                DecimalFormat vi = new DecimalFormat("#,##0.00");
                String vqtdItem = vi.format(qtdItem);
                qtdItemTab = vqtdItem;
                //
                valorUnitario1 = conecta.rs.getFloat("ValorUnitario");
                DecimalFormat vu1 = new DecimalFormat("#,##0.00");
                String valorUnitarioP = vu1.format(valorUnitario1);
                valorUnitario2 = valorUnitarioP;
                //
                valorTotalSoli = conecta.rs.getFloat("ValorTotal");
                DecimalFormat vut = new DecimalFormat("#,##0.00");
                String valorTotalP = vut.format(valorTotalSoli);
                valorTotalSoli1 = valorTotalP;
                //   jtotalItens.setText(Integer.toString(count)); // Converter inteiro em string para exibir na tela 
                dados.add(new Object[]{conecta.rs.getInt("IdProd"), conecta.rs.getString("DescricaoProd"), conecta.rs.getString("UnidadeProd"), qtdItemTab, valorUnitario2, valorTotalSoli1});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaItensAprovado.setModel(modelo);
        jTabelaItensAprovado.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTabelaItensAprovado.getColumnModel().getColumn(0).setResizable(false);
        jTabelaItensAprovado.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTabelaItensAprovado.getColumnModel().getColumn(1).setResizable(false);
        jTabelaItensAprovado.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTabelaItensAprovado.getColumnModel().getColumn(2).setResizable(false);
        jTabelaItensAprovado.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTabelaItensAprovado.getColumnModel().getColumn(3).setResizable(false);
        jTabelaItensAprovado.getColumnModel().getColumn(4).setPreferredWidth(50);
        jTabelaItensAprovado.getColumnModel().getColumn(4).setResizable(false);
        jTabelaItensAprovado.getColumnModel().getColumn(5).setPreferredWidth(70);
        jTabelaItensAprovado.getColumnModel().getColumn(5).setResizable(false);
        jTabelaItensAprovado.getTableHeader().setReorderingAllowed(false);
        jTabelaItensAprovado.setAutoResizeMode(jTabelaItensAprovado.AUTO_RESIZE_OFF);
        jTabelaItensAprovado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        alinharCamposItensTabelaAprovacao();
        conecta.desconecta();
    }

    public void alinharCamposItensTabelaAprovacao() {
        //
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        //
        jTabelaItensAprovado.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jTabelaItensAprovado.getColumnModel().getColumn(2).setCellRenderer(centralizado);
        jTabelaItensAprovado.getColumnModel().getColumn(3).setCellRenderer(direita);
        jTabelaItensAprovado.getColumnModel().getColumn(4).setCellRenderer(direita);
        jTabelaItensAprovado.getColumnModel().getColumn(5).setCellRenderer(direita);
    }

    public void objLog3() {
        objLogSys.setDataMov(dataModFinal);
        objLogSys.setHorarioMov(horaMov);
        objLogSys.setNomeModuloTela(nomeModuloTela3);
        objLogSys.setIdLancMov(Integer.valueOf(jIdAprova.getText()));
        objLogSys.setNomeUsuarioLogado(nameUser);
        objLogSys.setStatusMov(statusMov);
    }
}
