/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestor.Visao;

import gestor.Controle.ControleLogSistema;
import gestor.Controle.ControleVisitasDiversas;
import gestor.Dao.ConexaoBancoDados;
import Utilitarios.LimiteDigitos;
import Utilitarios.LimiteDigitosAlfa;
import Utilitarios.ModeloTabela;
import gestor.Modelo.LogSistema;
import gestor.Modelo.VisitasDiversas;
import static gestor.Visao.TelaLoginSenha.nameUser;
import static gestor.Visao.TelaModuloPrincipal.jDataSistema;
import static gestor.Visao.TelaModuloPrincipal.jHoraSistema;
import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author user
 */
public class TelaConsultaVisitasDiversasDir extends javax.swing.JInternalFrame {

    ConexaoBancoDados conecta = new ConexaoBancoDados();
    VisitasDiversas objViDi = new VisitasDiversas();
    ControleVisitasDiversas control = new ControleVisitasDiversas();
    ControleLogSistema controlLog = new ControleLogSistema();
    LogSistema objLogSys = new LogSistema();
    // Variáveis para gravar o log
    String nomeModuloTela = "Portaria:Cadastro de Visitas Diversas:Manutenção";
    String statusMov;
    String horaMov;
    String dataModFinal;
    //
    int flag;
    int acao;
    String caminho;
    String codVisita;
    String nomeVisita;
    int count = 0;

    /**
     * Creates new form TelaVisitasDiversas
     */
    public TelaConsultaVisitasDiversasDir() {
        initComponents();
        corCampo();
        formatarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPesqNomeVisitas = new javax.swing.JTextField();
        jBtPesqNome = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaVisitasDiversas = new javax.swing.JTable();
        jPanel30 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jtotalRegistros = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDataCadastro = new com.toedter.calendar.JDateChooser();
        jIdVisita = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jNomeVisita = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        FotoVisitaDiversas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRG = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jCPF = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jObservacao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCNH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jClasse = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("...::: Cadastro de Visitas Diversas :::...");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Nome Visitante:");

        jPesqNomeVisitas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jBtPesqNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestor/Imagens/Lupas_1338_05.gif"))); // NOI18N
        jBtPesqNome.setContentAreaFilled(false);
        jBtPesqNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesqNomeActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("Todos");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPesqNomeVisitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jPesqNomeVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtPesqNome)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabelaVisitasDiversas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTabelaVisitasDiversas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome da Visita", "RG", "CPF"
            }
        ));
        jTabelaVisitasDiversas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaVisitasDiversasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaVisitasDiversas);
        if (jTabelaVisitasDiversas.getColumnModel().getColumnCount() > 0) {
            jTabelaVisitasDiversas.getColumnModel().getColumn(0).setMinWidth(60);
            jTabelaVisitasDiversas.getColumnModel().getColumn(0).setMaxWidth(60);
            jTabelaVisitasDiversas.getColumnModel().getColumn(1).setMinWidth(225);
            jTabelaVisitasDiversas.getColumnModel().getColumn(1).setMaxWidth(225);
            jTabelaVisitasDiversas.getColumnModel().getColumn(2).setMinWidth(100);
            jTabelaVisitasDiversas.getColumnModel().getColumn(2).setMaxWidth(100);
            jTabelaVisitasDiversas.getColumnModel().getColumn(3).setMinWidth(100);
            jTabelaVisitasDiversas.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        jLabel63.setText("Total de Registros:");

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel63))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel63)
        );

        jPanel32.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        jtotalRegistros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtotalRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtotalRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
        );

        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jTabbedPane1.addTab("Listagem", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Data Cadastro");

        jDataCadastro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDataCadastro.setEnabled(false);

        jIdVisita.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jIdVisita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jIdVisita.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nome Completo da Visita");

        jNomeVisita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jNomeVisita.setEnabled(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Foto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(FotoVisitaDiversas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FotoVisitaDiversas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("RG");

        jRG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jRG.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("C.P.F");

        jCPF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jCPF.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Observação");

        jObservacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jObservacao.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("CNH");

        jCNH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jCNH.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Classe");

        jClasse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jClasse.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jObservacao)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRG)
                                    .addComponent(jCNH)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel6))
                                        .addGap(89, 89, 89))
                                    .addComponent(jCPF)
                                    .addComponent(jClasse)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jIdVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)))
                                .addComponent(jNomeVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(5, 5, 5)
                                .addComponent(jDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(1, 1, 1)
                                .addComponent(jIdVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addComponent(jNomeVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manutenção", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(360, 20, 476, 380);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtPesqNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesqNomeActionPerformed
        // TODO add your handling code here:
        count = 0;
        flag = 1;
        if (jPesqNomeVisitas.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe um nome ou parte dele para pesquisa.");
            jPesqNomeVisitas.requestFocus();
        } else {
            pesquisarNomesVisitas("SELECT * FROM VISITASDIVERSAS WHERE NomeVisita LIKE'%" + jPesqNomeVisitas.getText() + "%'");
        }
    }//GEN-LAST:event_jBtPesqNomeActionPerformed

    private void jTabelaVisitasDiversasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaVisitasDiversasMouseClicked
        // TODO add your handling code here:
        if (flag == 1) {
            String nomeVisita = "" + jTabelaVisitasDiversas.getValueAt(jTabelaVisitasDiversas.getSelectedRow(), 1);
            jPesqNomeVisitas.setText(nomeVisita);
            String idVisita = "" + jTabelaVisitasDiversas.getValueAt(jTabelaVisitasDiversas.getSelectedRow(), 0);
            jIdVisita.setText(idVisita);          
            // Limpar campos
            jIdVisita.setText("");
            jDataCadastro.setCalendar(Calendar.getInstance());
            jNomeVisita.setText("");
            FotoVisitaDiversas.setIcon(null);
            jRG.setText("");
            jCPF.setText("");
            jCNH.setText("");
            jClasse.setText("");
            jObservacao.setText("");
            conecta.abrirConexao();
            try {
                conecta.executaSQL("SELECT * FROM VISITASDIVERSAS WHERE NomeVisita='" + nomeVisita + "'");
                conecta.rs.first();
                jIdVisita.setText(String.valueOf(conecta.rs.getInt("IdVisita")));
                jDataCadastro.setDate(conecta.rs.getDate("DataCadastro"));
                jNomeVisita.setText(conecta.rs.getString("NomeVisita"));
                caminho = conecta.rs.getString("FotoVisita");
                javax.swing.ImageIcon i = new javax.swing.ImageIcon(caminho);
                FotoVisitaDiversas.setIcon(i);
                FotoVisitaDiversas.setIcon(new ImageIcon(i.getImage().getScaledInstance(FotoVisitaDiversas.getWidth(), FotoVisitaDiversas.getHeight(), Image.SCALE_DEFAULT)));
                jRG.setText(conecta.rs.getString("RgVisita"));
                jCPF.setText(conecta.rs.getString("CpfVisita"));
                jCNH.setText(conecta.rs.getString("CnhVisita"));
                jClasse.setText(conecta.rs.getString("ClasseVisita"));
                jObservacao.setText(conecta.rs.getString("ObsVisita"));
                conecta.desconecta();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "ERRO na pesquisa por nome" + e);
            }
        }
    }//GEN-LAST:event_jTabelaVisitasDiversasMouseClicked

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        count = 0;
        flag = 1;
        if (evt.getStateChange() == evt.SELECTED) {
            this.pesquisarTodasVisitas();
        } else {
            jtotalRegistros.setText("");
            limparTabela();
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FotoVisitaDiversas;
    private javax.swing.JButton jBtPesqNome;
    private javax.swing.JTextField jCNH;
    private javax.swing.JFormattedTextField jCPF;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTextField jClasse;
    private com.toedter.calendar.JDateChooser jDataCadastro;
    public static javax.swing.JTextField jIdVisita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNomeVisita;
    private javax.swing.JTextField jObservacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jPesqNomeVisitas;
    private javax.swing.JFormattedTextField jRG;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTabelaVisitasDiversas;
    private javax.swing.JLabel jtotalRegistros;
    // End of variables declaration//GEN-END:variables

    public void formatarCampos() {
        jNomeVisita.setDocument(new LimiteDigitos(50));
        jObservacao.setDocument(new LimiteDigitosAlfa(50));
        try {
            // Formatação para CPF
            MaskFormatter cpf = new MaskFormatter("###.###.###-##");
            jCPF.setFormatterFactory(new DefaultFormatterFactory(cpf));
            //Formatação para RG
            MaskFormatter rg = new MaskFormatter("##.###.###-##");
            jRG.setFormatterFactory(new DefaultFormatterFactory(rg));
        } catch (Exception e) {
        }
    }

    public void corCampo() {
        jIdVisita.setBackground(Color.white);
        jDataCadastro.setBackground(Color.white);
        jNomeVisita.setBackground(Color.white);
        jRG.setBackground(Color.white);
        jCPF.setBackground(Color.white);
        jCNH.setBackground(Color.white);
        jClasse.setBackground(Color.white);
        jObservacao.setBackground(Color.white);
    }

    public void Novo() {
        // Limpar campos
        jIdVisita.setText("");
        jDataCadastro.setCalendar(Calendar.getInstance());
        jNomeVisita.setText("");
        FotoVisitaDiversas.setIcon(null);
        jRG.setText("");
        jCPF.setText("");
        jCNH.setText("");
        jClasse.setText("");
        jObservacao.setText("");
        //Habilitar/Desabilitar campos
        jDataCadastro.setEnabled(true);
        jNomeVisita.setEnabled(true);
        jRG.setEnabled(true);
        jCPF.setEnabled(true);
        jCNH.setEnabled(true);
        jClasse.setEnabled(true);
        jObservacao.setEnabled(true);      
    }

    public void Alterar() {
        //Habilitar/Desabilitar campos
        jDataCadastro.setEnabled(true);
        jNomeVisita.setEnabled(true);
        jRG.setEnabled(true);
        jCPF.setEnabled(true);
        jCNH.setEnabled(true);
        jClasse.setEnabled(true);
        jObservacao.setEnabled(true);       
    }

    public void Excluir() {
        // Limpar campos
        jIdVisita.setText("");
        jDataCadastro.setDate(null);
        jNomeVisita.setText("");
        FotoVisitaDiversas.setIcon(null);
        jRG.setText("");
        jCPF.setText("");
        jCNH.setText("");
        jClasse.setText("");
        jObservacao.setText("");
        //Habilitar/Desabilitar campos
        jDataCadastro.setEnabled(!true);
        jNomeVisita.setEnabled(!true);
        jRG.setEnabled(!true);
        jCPF.setEnabled(!true);
        jCNH.setEnabled(!true);
        jClasse.setEnabled(!true);
        jObservacao.setEnabled(!true);        
    }

    public void Salvar() {
        //Habilitar/Desabilitar campos
        jDataCadastro.setEnabled(!true);
        jNomeVisita.setEnabled(!true);
        jRG.setEnabled(!true);
        jCPF.setEnabled(!true);
        jCNH.setEnabled(!true);
        jClasse.setEnabled(!true);
        jObservacao.setEnabled(!true);      
    }

    public void Cancelar() {
        //Habilitar/Desabilitar campos
        jDataCadastro.setEnabled(!true);
        jNomeVisita.setEnabled(!true);
        jRG.setEnabled(!true);
        jCPF.setEnabled(!true);
        jClasse.setEnabled(!true);
        jObservacao.setEnabled(!true);
        jObservacao.setEnabled(!true);       
    }

    public void pesquisarTodasVisitas() {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Nome da Visita", "RG", "CPF"};
        conecta.abrirConexao();
        conecta.executaSQL("SELECT * FROM VISITASDIVERSAS");;
        try {
            conecta.rs.first();
            do {
                count = count + 1;
                jtotalRegistros.setText(Integer.toString(count)); // Converter inteiro em string para exibir na tela
                dados.add(new Object[]{conecta.rs.getInt("IdVisita"), conecta.rs.getString("NomeVisita"), conecta.rs.getString("RgVisita"), conecta.rs.getString("CpfVisita")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não existe dados a ser exibido!!!");
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaVisitasDiversas.setModel(modelo);
        jTabelaVisitasDiversas.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTabelaVisitasDiversas.getColumnModel().getColumn(0).setResizable(false);
        jTabelaVisitasDiversas.getColumnModel().getColumn(1).setPreferredWidth(225);
        jTabelaVisitasDiversas.getColumnModel().getColumn(1).setResizable(false);
        jTabelaVisitasDiversas.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTabelaVisitasDiversas.getColumnModel().getColumn(2).setResizable(false);
        jTabelaVisitasDiversas.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTabelaVisitasDiversas.getColumnModel().getColumn(3).setResizable(false);
        jTabelaVisitasDiversas.getTableHeader().setReorderingAllowed(false);
        jTabelaVisitasDiversas.setAutoResizeMode(jTabelaVisitasDiversas.AUTO_RESIZE_OFF);
        jTabelaVisitasDiversas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        alinharCamposTabelaVisitas();
        conecta.desconecta();
    }

    public void pesquisarNomesVisitas(String sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Codigo", "Nome da Visita", "RG", "CPF"};
        conecta.abrirConexao();
        conecta.executaSQL(sql);;
        try {
            conecta.rs.first();
            do {
                count = count + 1;
                jtotalRegistros.setText(Integer.toString(count)); // Converter inteiro em string para exibir na tela
                dados.add(new Object[]{conecta.rs.getInt("IdVisita"), conecta.rs.getString("NomeVisita"), conecta.rs.getString("RgVisita"), conecta.rs.getString("CpfVisita")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não existe dados a ser exibido!!!");
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaVisitasDiversas.setModel(modelo);
        jTabelaVisitasDiversas.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTabelaVisitasDiversas.getColumnModel().getColumn(0).setResizable(false);
        jTabelaVisitasDiversas.getColumnModel().getColumn(1).setPreferredWidth(225);
        jTabelaVisitasDiversas.getColumnModel().getColumn(1).setResizable(false);
        jTabelaVisitasDiversas.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTabelaVisitasDiversas.getColumnModel().getColumn(2).setResizable(false);
        jTabelaVisitasDiversas.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTabelaVisitasDiversas.getColumnModel().getColumn(3).setResizable(false);
        jTabelaVisitasDiversas.getTableHeader().setReorderingAllowed(false);
        jTabelaVisitasDiversas.setAutoResizeMode(jTabelaVisitasDiversas.AUTO_RESIZE_OFF);
        jTabelaVisitasDiversas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        alinharCamposTabelaVisitas();
        conecta.desconecta();
    }

    public void limparTabela() {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Codigo", "Nome da Visita", "RG", "CPF"};
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaVisitasDiversas.setModel(modelo);
        jTabelaVisitasDiversas.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTabelaVisitasDiversas.getColumnModel().getColumn(0).setResizable(false);
        jTabelaVisitasDiversas.getColumnModel().getColumn(1).setPreferredWidth(225);
        jTabelaVisitasDiversas.getColumnModel().getColumn(1).setResizable(false);
        jTabelaVisitasDiversas.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTabelaVisitasDiversas.getColumnModel().getColumn(2).setResizable(false);
        jTabelaVisitasDiversas.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTabelaVisitasDiversas.getColumnModel().getColumn(3).setResizable(false);
        jTabelaVisitasDiversas.getTableHeader().setReorderingAllowed(false);
        jTabelaVisitasDiversas.setAutoResizeMode(jTabelaVisitasDiversas.AUTO_RESIZE_OFF);
        jTabelaVisitasDiversas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        modelo.getLinhas().clear();
    }

    public void alinharCamposTabelaVisitas() {
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        //
        jTabelaVisitasDiversas.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        jTabelaVisitasDiversas.getColumnModel().getColumn(2).setCellRenderer(centralizado);
        jTabelaVisitasDiversas.getColumnModel().getColumn(3).setCellRenderer(centralizado);
    }

    public void buscarID() {
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM VISITASDIVERSAS");
            conecta.rs.last();
            jIdVisita.setText(conecta.rs.getString("IdVisita"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Nao foi possível pegar código do advogado.\nERRO: " + ex);
        }
        conecta.desconecta();
    }

    public void VerificarEntVisitas() {
        statusMov = "Excluiu";
        horaMov = jHoraSistema.getText();
        dataModFinal = jDataSistema.getText();
        objViDi.setIdVisita(Integer.valueOf(jIdVisita.getText()));
        conecta.abrirConexao();
        try {
            conecta.executaSQL("SELECT * FROM ITENSVISITASDIVERSAS WHERE IdVisita='" + jIdVisita.getText() + "'");
            conecta.rs.first();
            codVisita = conecta.rs.getString("IdVisita");
            conecta.desconecta();
        } catch (SQLException ex) {
        }
        if (jIdVisita.getText().equals(codVisita)) {
            JOptionPane.showMessageDialog(rootPane, "Esse registro não poderá ser excluido, o mesmo está relacionado a ENTRADA DE VISITAS DIVERSAS!!!");
        } else {
            try {
                conecta.executaSQL("SELECT * FROM ENTRADAVEICULOCARGA WHERE IdVisita='" + jIdVisita.getText() + "'");
                conecta.rs.first();
                codVisita = conecta.rs.getString("IdVisita");
                conecta.desconecta();
            } catch (SQLException ex) {
            }
            if (jIdVisita.getText().equals(codVisita)) {
                JOptionPane.showMessageDialog(rootPane, "Esse registro não poderá ser excluido, o mesmo está relacionado ao documento de ENTRADA DE VEICULOS DE CARGAS!!!");
            } else {
                try {
                    conecta.executaSQL("SELECT * FROM ITENSVEICULOSTERCEIRO WHERE IdVisita='" + jIdVisita.getText() + "'");
                    conecta.rs.first();
                    codVisita = conecta.rs.getString("IdVisita");
                    conecta.desconecta();
                } catch (SQLException ex) {
                }
                if (jIdVisita.getText().equals(codVisita)) {
                    JOptionPane.showMessageDialog(rootPane, "Esse registro não poderá ser excluido, o mesmo está relacionado ao documento de ENTRADA DE VEICULOS DE TERCEIROS!!!");
                } else {
                    int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o interno selecionado?", "Confirmação",
                            JOptionPane.YES_NO_OPTION);
                    if (resposta == JOptionPane.YES_OPTION) {
                        objViDi.setIdVisita(Integer.valueOf(jIdVisita.getText()));
                        control.excluirVisitas(objViDi);
                        objLog();
                        controlLog.incluirLogSistema(objLogSys); // Grava o log da operação
                        JOptionPane.showMessageDialog(rootPane, "Registro EXCLUIDO com sucesso !!!");
                        Excluir();
                    }
                    conecta.desconecta();
                }
            }
        }
    }

    public void objLog() {
        objLogSys.setDataMov(dataModFinal);
        objLogSys.setHorarioMov(horaMov);
        objLogSys.setNomeModuloTela(nomeModuloTela);
        objLogSys.setIdLancMov(Integer.valueOf(jIdVisita.getText()));
        objLogSys.setNomeUsuarioLogado(nameUser);
        objLogSys.setStatusMov(statusMov);
    }

    // Executar programa externo da webcam
    public void webCam() {
        try {
            Process p = Runtime.getRuntime().exec("C:\\SysConp\\MyCam/MyCam.exe");
            if (p.exitValue() == 0) {
                System.out.println("Programa terminou normalmente");
            }
        } catch (Exception e) {
        }
    }
}
